### PR TITLE
[18.01] Fix common_startup.sh for galaxy tarballs

### LINKED ISSUE #5466: dev branch common_startup.sh fails with .git directory error
Log from a TravisCI tool test using Galaxy ``master`` (my tool test fails, which is correct):
https://travis-ci.org/peterjc/kodoja_galaxy/jobs/338504945

```
$ bash scripts/common_startup.sh --no-create-venv --dev-wheels
Initializing config/migrated_tools_conf.xml from migrated_tools_conf.xml.sample
Initializing config/shed_tool_conf.xml from shed_tool_conf.xml.sample
Initializing config/shed_tool_data_table_conf.xml from shed_tool_data_table_conf.xml.sample
Initializing config/shed_data_manager_conf.xml from shed_data_manager_conf.xml.sample
Initializing tool-data/shared/ucsc/builds.txt from builds.txt.sample
Initializing tool-data/shared/ucsc/manual_builds.txt from manual_builds.txt.sample
Initializing static/welcome.html from welcome.html.sample
Requirement already satisfied: pip>=8.1 in /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages
Collecting bx-python==0.7.3 (from -r requirements.txt (line 2))
  Downloading https://wheels.galaxyproject.org/packages/bx_python-0.7.3-cp27-cp27mu-manylinux1_x86_64.whl (2.1MB)
    100% |████████████████████████████████| 2.2MB 23.8MB/s 
...
```

Log from matching TravisCI tool test using Galaxy ``dev``, ``scripts/common_startup.sh`` fails:
https://travis-ci.org/peterjc/kodoja_galaxy/jobs/338504945

```
$ bash scripts/common_startup.sh --no-create-venv --dev-wheels
Initializing config/migrated_tools_conf.xml from migrated_tools_conf.xml.sample
Initializing config/shed_tool_conf.xml from shed_tool_conf.xml.sample
Initializing config/shed_tool_data_table_conf.xml from shed_tool_data_table_conf.xml.sample
Initializing config/shed_data_manager_conf.xml from shed_data_manager_conf.xml.sample
Initializing tool-data/shared/ucsc/builds.txt from builds.txt.sample
Initializing tool-data/shared/ucsc/manual_builds.txt from manual_builds.txt.sample
Initializing static/welcome.html from welcome.html.sample
fatal: Not a git repository (or any of the parent directories): .git

The command "bash scripts/common_startup.sh --no-create-venv --dev-wheels" failed and exited with 128 during .
```

### PR DESCRIPTION
**Pull request by nsoranzo**
Do not assume git is installed and the `.git` directory is present.

Fix #5466.

Includes also a backport of https://github.com/galaxyproject/galaxy/pull/5375.

### CODE REVIEW

File: scripts/common_startup.sh [hunk 1]
```diff
@@ -65,30 +77,23 @@ for rmfile in $RMFILES; do
...
+            ;;
+        *)
+            # Ensure nodeenv is installed
+            DEV_WHEELS=1
+            # SKIP_CLIENT_BUILD will default to false, but can be overridden by the command line argument
+            ;;
+    esac
+else
+    GIT_BRANCH=0
+    DEV_WHEELS=1
```
Comment (natefoo) [inline scripts/common_startup.sh:96]: Dev wheels will be installed even if we don't need to build the client, is this desirable?

Comment (nsoranzo) [reply scripts/common_startup.sh:96]: Since we don't know which branch the tarball comes from, we have to always build the client the first time.

Comment (natefoo) [reply scripts/common_startup.sh:96]: We should consider committing the client_build_hash.txt in release branches, but this is a good solution for now.

**Review by natefoo — APPROVED** [review]
