### PR TITLE
Reduce unnecessary requests when browsing tool repositories in Admin Panel

### LINKED ISSUE #18588: Browsing tool repositories in the Admin Panel creates too many requests
**Describe the bug**
Browsing tool repositories, in the Admin Panel, creates too many redundant requests too frequently.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0 (likely older versions too)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**Browser and Operating System**
Operating System: Linux
Browser: Firefox, Chrome

**To Reproduce**
1. Open or search repositories in http://127.0.0.1:8081/admin/toolshed
2. Expand one of the repositories and observe the client starts polling even if there is no expected change in the status
3. Keep expanding repositories, the polling increases for each one of them

**Expected behavior**
It is ok to get the initial status but the polling should be used only if there is an expected change i.e. waiting for a non-terminal tool installation status, etc.

**Screenshots**
TooManyRequestsBrowsingTools

**Additional context**
Noticed by @bgruening 
After some time it could start throwing 500 errors due to the maximum database connections reached. This could be a symptom of another issue with the session of the tool_shed_install model.

### PR DESCRIPTION
**Pull request by davelopez**
Fixes #18588

This ensures that a browser tab in the background will not poll for the status.

In addition:
- Converts RepositoryDetails/Index.vue to composition API.
- Makes the install/uninstall button more responsive to avoid multiple clicks

    ### Before
    
    ToolInstallBefore
    
    
    ### After
    
    ToolInstallAfter

## How to test the changes?
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/Toolshed/RepositoryDetails/Index.vue [hunk 1]
```diff
@@ -1,3 +1,228 @@
...
+        if (repoRevision.status !== x.status) {
+            x.status = repoRevision.status;
+            x.installed = repoRevision.installed;
+        }
+    });
+
+    repoTable.value = [...repoTable.value];
+}
+
+function isAnyChangeExpected() {
```
Comment (mvdbeek) [inline client/src/components/Toolshed/RepositoryDetails/Index.vue]: I think we can replace this with a constant of true ? 😆 
We're always expecting changes, from another tab or the API.

Comment (mvdbeek) [reply client/src/components/Toolshed/RepositoryDetails/Index.vue]: If we're trying to reduce polling frequency, could we instead cycle through the list of repositories, or filter `/api/tool_shed_repositories` by update_time, or filter `api/tool_shed_repositories` by the expanded repository ids ? But is this really such a problem that it requires addressing ? Even if you expand 100 repositories that doesn't really seem like it should be a problem.

Comment (davelopez) [reply client/src/components/Toolshed/RepositoryDetails/Index.vue]: > I think we can replace this with a constant of true ? 😆

Ooff, you just killed me :finnadie:  :rofl: 
I didn't think it could have been updated somewhere else :sweat: 

> Even if you expand 100 repositories that doesn't really seem like it should be a problem.

I think the problem was not polling for every expanded repository, but rather the accumulation of timers that even if you go away from that page they keep requesting changes for some reason :shrug: 

I'll have a look at those API filters, but even just polling indefinitely for an expanded repository will produce less requests and avoid it completely when you are in a different tab, etc. So that is something :sweat_smile:

Comment (mvdbeek) [reply client/src/components/Toolshed/RepositoryDetails/Index.vue]: Yeah, for sure, the changes look solid to me, but I think I'd prefer being a little dumber here and poll for anything that is expanded.

Comment (davelopez) [reply client/src/components/Toolshed/RepositoryDetails/Index.vue]: Done!

**Review by mvdbeek — APPROVED** [review]
Thank you!
