### PR TITLE
Beta History: allow search datasets by name tag using `#`

### LINKED ISSUE #13873: Beta History: Cannot filter name tags: filterText does not find #name tags unless provided "name:"
The `filterText` field and advanced filter settings do not find name tags, unless you provide the leading `name:`.

**To Reproduce**
1. On the beta history panel, given that you have a name tag (e.g.: `#tag1`/`name:tag1`),
2. Search for it without the leading `name:` (e.g.: "tag1" or "#tag1"). Will return no results.
3. Search for it with the leading `name:` (e.g.: "name:tag1"). Will return the datasets with the tag.

https://user-images.githubusercontent.com/78516064/166977835-e38a5feb-dc85-4c1b-9944-fcd1963d2ef6.mov

### PR DESCRIPTION
**Pull request by davelopez**
Fixes #13873

Also, allow search by `contains` instead of `equals` tag name match

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] Instructions for manual testing are as follows:
  - Follow instructions on #13873

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

File: client/src/store/historyStore/model/filtering.js [hunk 1]
```diff
@@ -49,12 +58,18 @@ function equals(attribute, query = null, converter = null) {
...
  */
-function contains(attribute, query = null) {
+function contains(attribute, query = null, converter = null) {
     return {
         attribute,
+        converter,
         query: query || `${attribute}-contains`,
         handler: (v, q) => {
+            if (converter) {
+                q = converter(q);
```
Comment (guerler) [inline client/src/store/historyStore/model/filtering.js:72]: Maybe we should convert `v = converter(v)` here, to make sure that they are always formatted in the same fashion.

File: client/src/store/historyStore/model/filtering.js [hunk 2]
```diff
@@ -107,7 +122,7 @@ const validFilters = {
     visible: equals("visible", "visible", toBool),
     name: contains("name"),
     state: equals("state"),
-    tag: contains("tags", "tag"),
+    tag: contains("tags", "tag-contains", expandNameTag),
```
Comment (guerler) [inline client/src/store/historyStore/model/filtering.js:125]: Can you explain why we change to `tag-contains` here, I thought this only correlates to the key in the filter text?

**Review by dannon — APPROVED** [review]
