### PR TITLE
[24.1] fix no-op workflow "relabel" shouldn't result in a notification

### LINKED ISSUE #18436: No-op workflow "relabel" shouldn't result in a notification.
Watching @mvdbeek do the advanced workflow training - and every time he gives a new tool or step a label it pops up a message "Label '' updated to 'the name entered' in workflow report", but that workflow report clearly didn't contain that label. I think I meant this message to only appear if the workflow report actually changed.

### PR DESCRIPTION
**Pull request by ElectronicBlueberry**
closes #18436

adds a check if markdown has changed before emitting a notification

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/Workflow/Editor/Actions/stepActions.ts [hunk 1]
```diff
@@ -87,17 +87,23 @@ export class LazySetLabelAction extends LazyMutateStepAction<"label"> {
     run() {
         const markdown = this.stateStore.report.markdown ?? "";
         const newMarkdown = replaceLabel(markdown, this.labelType, this.fromValue as string, this.toValue as string);
-        this.stateStore.report.markdown = newMarkdown;
-        this.toast(this.fromValue ?? "", this.toValue ?? "");
+
+        if (markdown !== newMarkdown) {
```
Comment (mvdbeek) [inline client/src/components/Workflow/Editor/Actions/stepActions.ts]: Can we factor this out into a separate function to avoid the repetition ?

**Review by mvdbeek — APPROVED** [review]
