### PR TITLE
Fix Workflow Editor Zoom

### LINKED ISSUE #15370: WF editor mouse-wheel/touchpad zooming too coarse
**Describe the bug**
When trying to zoom in or out of the WF display in the WF editor using the mouse wheel or the touchpad (instead of using the dedicated UI buttons), it's almost all or nothing.

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.org at 23.0

### PR DESCRIPTION
**Pull request by ElectronicBlueberry**
Fixes #15370

Fixes coarse zoom by using default zoom behavior. Please let me know if this works with pinch-zoom, as my touch-pad does not support pinch-zooming on website content. If it does not, I have another solution in mind.

Also fixes an issue with stuck tooltips, by using default tooltips instead of bootstrap vue ones.
Since bootstrap vue tooltips do not work on disabled buttons. Since the zoom button get's disabled on highest zoom, the label got stuck, even when zooming back out.

Also does some minor refactoring.

### CODE REVIEW

File: client/src/components/Workflow/Editor/composables/d3Zoom.ts [hunk 1]
```diff
@@ -29,20 +29,6 @@ export function useZoom(
                 .translate(transform.value.x, transform.value.y)
                 .scale(transform.value.k);
             d3Zoom.transform(d3Selection, updatedTransform);
-
```
Comment (mvdbeek) [inline client/src/components/Workflow/Editor/composables/d3Zoom.ts:32]: Wow, that's what you get for copy-pasting from example code. Works nicely!

**Comment by mvdbeek** [comment]
Awesome, works great with pinch to zoom and trackpad. Thanks @ElectronicBlueberry!
