### PR TITLE
[25.0] Error on duplicate labels

### LINKED ISSUE #20230: Outputs with duplicate workflow labels are missing from the Invocation view’s Outputs tab
**Describe the bug**

When a workflow defines multiple outputs using the same label, only one of those outputs appears in the Outputs tab of the invocation view—even if you’ve selected them all.

**To Reproduce**

1. Create a workflow that produces two or more outputs.
2. Assign the same label to at least two of those outputs.
3. Run the workflow
4. In the invocation view, switch to the Outputs tab.

**Expected behavior**
Every output that was ticked in the invocation should be listed—labels shouldn’t prevent outputs from appearing.

**Screenshots**

**Additional context**

Related to:  https://github.com/galaxyproject/galaxy/pull/20073

### PR DESCRIPTION
**Pull request by ElectronicBlueberry**
closes #20230

Treats duplicate output labels as errors, and warns the user more clearly about them.
Also fixes non-output labels being marked as duplicate.

image

In the future we could add an option to fix these automatically, but I think that is beyond the scope of this bug-fix

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/Workflow/Editor/Index.vue [hunk 1]
```diff
@@ -878,7 +897,7 @@ export default {
         async saveOrCreate() {
             if (this.hasInvalidConnections) {
```
Comment (davelopez) [inline client/src/components/Workflow/Editor/Index.vue]:
```suggestion
            if (this.hasInvalidConnections ||this.hasDuplicateOutputs) {
```

Do we want to display the confirmation also in this case?

Comment (ElectronicBlueberry) [reply client/src/components/Workflow/Editor/Index.vue]: good catch!

**Review by davelopez — APPROVED** [review]
Thank you!
