### PR TITLE
Visible marker to distinguish required/optional tool params

### LINKED ISSUE #14627: Visible marker to distinguish required/optional tool params
**Describe the bug**
Tool params that are marked up with `optional=true` aren't distinguished from non-optional params in the UI. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.01 (muongalaxy.stfc.ac.uk) and 22.05 (usegalaxy.eu)

**Expected behavior**
There should be a clear distinction between required and optional fields in the tool form UI (both visible and screen reader accessible).

There are a couple of common ways this is done elsewhere on the web:
- asterisk on required fields (usually red) 
- text '(optional)' after optional fields (often smaller and/or greyed-out)

The best option for Galaxy probably depends on whether the majority of fields across all tools are optional or required.

--

**Screenshots**
The second and fourth fields in this screenshot are optional, but there's no way to tell.
Screenshot of tool form containing four fields with identical formatting

### PR DESCRIPTION
**Pull request by ElectronicBlueberry**
Fixes #14627

# Param Hints

Adds hints for required, optional and empty but required form elements.

The following screenshot shows one required and empty, one optional parameter, and one boolean parameter. Since boolean parameters can not be empty, the required / optional hint is not shown.

image

The next screenshot shows a required but empty param, next to two required params containing values.

image

## Refactor

This PR also refactors the FormElement component, bringing several fixes and some changes.

 - The collapse and connect buttons are now keyboard navigatable
 - The default icons for these buttons have been updated to the current font awesome version used in galaxy, and are now font-awesome icon components. This change now requires calling `library.add(...)` in any place a custom icon is to be used. These changes have been applied accordingly.
 - The components css has been moved to the component, and made scoped.
 - Dynamic props (props mapped to attributes, when no attributes object is provided) have been deprecated for the FormElement component. Reasons for this are (in no particular order):
   * It is prone to breaking. Adding an attributes prop will disable dynamic props, which is not clear and might lead to unforeseen behavior.
   * It is very hard to type-check, which will become relevant once we introduce typescript.
   * They are no longer reactive in the composition api (though this might be a bug)
   
  Existing uses of this feature have been rewritten accordingly. Attributes are still mapped dynamically to not break the legacy FormParameter components.

## Tests

New test cases have been added to account for the new features and changes.

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/Form/FormElement.vue [hunk 1]
```diff
@@ -1,270 +1,353 @@
...
+                :type="props.type"
                 :attributes="attrs" />
-            <FormInput v-else :id="id" v-model="currentValue" :area="attrs['area']" />
+            <FormInput v-else :id="props.id" v-model="currentValue" :area="attrs['area']" />
         </div>
-        <div v-if="showPreview" class="ui-form-preview" v-html="previewText" />
-        <span v-if="!!helpText" class="ui-form-info form-text text-muted" v-html="helpText" />
+
+        <div v-if="showPreview" class="ui-form-preview pt-1 pl-2 mt-1">{{ previewText }}</div>
+        <span v-if="Boolean(helpText)" class="ui-form-info form-text text-muted" v-html="helpText" />
```
Comment (ElectronicBlueberry) [inline client/src/components/Form/FormElement.vue:271]: I was unable to find a case where setting the previewText as escaped html is different from setting the text, but would like someone to double check this, in case I unintentionally broke something,

**Review by dannon — APPROVED** [review]
Thanks for the rebase, this looks great to me.  I'll let the tests finish and then will merge it on in.

**Comment by dannon** [comment]
Test failure is unrelated, will follow up separately.

**Comment by guerler** [comment]
Noticed an issue here with non-optional fields, indicating that they are optional: 
image
Maybe neither assume required nor optional by default?

**Comment by ElectronicBlueberry** [comment]
Good idea, I'll do that in a follow-up PR.
I think it would be best in the long run to properly mark these fields though.
