### PR TITLE
Vue integration, bibtex replacement

### LINKED ISSUE #4906: bib2json regression in dev
This piece of code was meant to prevent the need to hack ``bibtex.js`` so we could just pull it npm. I don't think it works though - ``_`` doesn't mutate its arguments it creates new ones. I tried setting the properties directly and that doesn't seem to work either.

```
    _.extend(parseBibtex.ENTRY_TYPES_, {
        online: 998, // Galaxy MOD: Handle @online entries for preprints.
        data: 999 // Galaxy MOD: Handle @data citations coming from figshare.
    });
```

The latest Github variant of this package supports online but it hasn't been published to npm in a very long time. figshare DOIs no longer return these ``data`` entries so I'd be fine with just getting the latest variant of this from GIthub somehow - otherwise I think we need a better hack or need to restore our variant.

Ping @dannon - any thoughts?

I have a test case to verify some of this stuff but it fails obviously - let me know if that would be helpful.

### PR DESCRIPTION
**Pull request by dannon**
The original plan was to use the citations bugfix/overhaul as a simple vehicle to show off the Vue integration, but this includes quite a few more notable bits from the journey.

I'll elaborate more, and plan to write guidelines for best practices, but in short this pr:
1) Adds Vue
2) Adds build support for Vue Single File Components (SFCs)
3) Cherrypicks @anuprulez work from the demo Vue admin/userkeys display
4) Updates that to a single file component, so people can see the transition
5) Adds support for using dependencies straight out of `node_modules`.  This *WILL NOT WORK* for stuff `require()d`, but for components which are 100% bundled (as should be everything new), it's way cleaner and easier, and the right way to do it.
6) Should fix #4906; replaces the bibtex lib with two separate components that are much more flexible and extensible.
7) Adds axios (https://github.com/axios/axios) as an HTTP client.  It's really, really nice.

Neither of these displays really benefit from vuex, ~~but I'm going to try to work an example of that in as well~~ (to keep it simple, will pursue Vuex in a separate PR)

8) Adds two new application entrypoints, removing old 'require'-based entries for both the masthead and workflow editor.  This ideally would have been a separate PR since it's a pretty big step forward, but it was a requirement for getting citations.vue working correctly.  (basically, I managed to pick the most entangled component ever to use as a vue conversion example -- d'oh).  This *dramatically* cuts down on the number of files fetched on older pages.

Workflow editor load times, before, then after.  Similar performance increases for data libraries, trackster, and circster.

image
image

9) Bundling of libraries, trackster, circster as well as the aforementioned workflow editor, with similar performance gains.   Libraries got cut down by about 80 requests, halving the time it takes to load.

### CODE REVIEW

File: client/galaxy/scripts/apps/admin.js [hunk 1]
```diff
@@ -91,6 +94,17 @@ window.app = function app(options, bootstrapped) {
             );
         },
 
+        show_user_api_keys: function() {
+            // TODO refactor into a reusable Vue component display mechanism.
+            var z = document.createElement('div');
+            this.page.display(z);
+            new Vue({
```
Comment (jxtx) [inline client/galaxy/scripts/apps/admin.js]: I think you can simplify this to 

```
new Vue(UserAPIKeys).$mount(z)
```

Which will make it easier to generalize later because you can just pass the component in, no need for template.

Comment (dannon) [reply client/galaxy/scripts/apps/admin.js]: Nice, trying that out now.

Comment (dannon) [reply client/galaxy/scripts/apps/admin.js]: @jxtx Works great, thanks!

**Comment by anuprulez** [comment]
@dannon thank you!

File: client/galaxy/scripts/components/citations.vue [hunk 2]
```diff
@@ -0,0 +1,196 @@
...
+            <div v-if="source == 'history'" style="padding:5px 10px">
+                <b>Warning: This is a experimental feature.</b> Most Galaxy
+                tools will not annotate citations explicitly at this time. When
+                writing up your analysis, please manually review your histories
+                and find all references that should be cited in order to
+                completely describe your work. Also, please remember to <a
+                href="https://galaxyproject.org/citing-galaxy">cite Galaxy</a>.
+            </div>
+        </div>
+        <div class="citations-bibtex toolFormBody" style="padding:5px 10px">
```
Comment (anuprulez) [inline client/galaxy/scripts/components/citations.vue]: Citations.vue template uses same inline style `style="padding:5px 10px" `more than once. Can we use the same css class at these places?
Thanks!

File: client/galaxy/scripts/components/citations.vue [hunk 3]
```diff
@@ -0,0 +1,196 @@
...
+
+            var ref = "";
+            var authorsAndYear = `${this._asSentence(
+                (fields.author ? fields.author : "") + (fields.year ? ` (${fields.year})` : "")
+            )} `;
+            var title = fields.title || "";
+            var pages = fields.pages ? `pp. ${fields.pages}` : "";
+            var address = fields.address;
+            if (entryType == "article") {
+                var volume =
```
Comment (anuprulez) [inline client/galaxy/scripts/components/citations.vue:106]: We can use `let` for block-level variables instead of `var` as we have started using ES6 features.

File: client/galaxy/scripts/components/citations.vue (hunk 2 above)
Comment (dannon) [reply client/galaxy/scripts/components/citations.vue]: Yeah, we shouldn't use inline styles anywhere like this (for the most part).  This was a quick translation from the old backbone version without any updates.

File: client/galaxy/scripts/components/citations.vue (hunk 3 above)
Comment (dannon) [reply client/galaxy/scripts/components/citations.vue:106]: Yep, we should.  Same comment as above; right now this is pulled straight from the old backbone classes and needs more updates.

File: client/galaxy/scripts/components/citations.vue (hunk 2 above)
Comment (dannon) [reply client/galaxy/scripts/components/citations.vue]: (in fact, these styles will be pushed into the `<style>` component block)

**Comment by dannon** [comment]
I was going to work on Vuex in this branch as well, but the PR is going to get unwieldy.  I'm going to clean this up and take it out of WIP, and then separately I'm working on implementing the toolbox and admin whitelist (shared state of the tool list) as vue components, using vuex and experimenting with a shared vue table component (that we can use for all grids, etc.).

**Comment by anuprulez** [comment]
@dannon @bgruening Can we take inputs from this PR related to VueJS and convert some other mako to vue? Thanks!

**Comment by jxtx** [comment]
Yes, I'd like to see this committed with the least amount of complexity possible. Then other people can play with different extensions (e.g. I want to try vue-strap with our styles).

**Comment by dannon** [comment]
@jxtx Yeah, that's the plan.  No new additions in this branch, just need to fix citations in the workflow editor toolpanel and it's good to merge (more discussion in IRC this morning if interested).

**Comment by dannon** [comment]
Qunit failures are legit, should be the last thing I need to fix here.

**Comment by dannon** [comment]
Sorry this kept growing, all -- I picked citations as a vehicle for implementing the framework here since it was what I was already looking at, thinking it was a pretty isolated bit of code.  Turns out they touch basically everything through dependencies, though.

**Comment by dannon** [comment]
Back to WIP while I fix another entrypoint.

Latest update:  I'm working on bundling everything entered via galaxy.panels.mako; it was inevitable that we'd have to do this, and is a really nice thing to have done moving forward.  Hopefully will have this done today.

**Comment by dannon** [comment]
Ok, fixed require-based entrypoints I found that ended up pulling in citations.vue.  Had to make a few extra bundles for now that I want to revisit and refactor a bit, but it's a stepping stone towards webpacking everything (which is a big next step), and it dramatically improves loading speed of the pages affected.  Taking out of WIP, should be good to go, but of course if anything's broken, I'll follow up on it quickly.

I have a few ideas about the remaining disabled karma/qunit tests, but nothing concrete; will keep working on those, too, though if someone else fixes them first that's awesome.

File: client/galaxy/scripts/components/citations.vue [hunk 4]
```diff
@@ -0,0 +1,208 @@
...
+                Show BibTeX
+            </button>
+            <button v-else type="button" v-on:click="toggleViewRender" class="btn btn-xs" title="Return to formatted citation list.">
+                <i class="fa fa-times"></i>
+                Hide BibTeX
+            </button>
+        </div>
+        <div class="toolFormBody citationPadding">
+            <div v-if="source === 'histories'" class="citation-padding">
+                <b>Warning: This is a experimental feature.</b> Most Galaxy
```
Comment (jmchilton) [inline client/galaxy/scripts/components/citations.vue]: I'll follow up in a subsequent PR and rework this block - I don't think this feature is so experimental anymore - most new tools have citations and we have done a good job back annotating as well.

Comment (dannon) [reply client/galaxy/scripts/components/citations.vue]: @jmchilton I'm happy to simplify that logic and remove the toggle right now.

Comment (jmchilton) [reply client/galaxy/scripts/components/citations.vue]: I like encouraging people to cite Galaxy though - that bit should stay ;).

**Comment by jmchilton** [comment]
Comments simply on the citations stuff:

These are operating on slightly different lists of citations but here is 17.09's rendering of a fairly challenging set of citations vs this branch's.

17.09:
screen shot 2017-11-21 at 9 35 13 am

This branch:
screen shot 2017-11-21 at 9 31 11 am

They both are ... bad. 17.09 is a little better at properly formatting the fields (e.g. journals in italics) and not dropping fields (e.g. the publisher), this branch is handling unicode much better, 17.09 is formatting the LaTeX embedded math a little more cleanly to my eye. While I prefer the presentation of 17.09 - I think it is close enough that we should probably go with what is here if we feel the libraries these are based on are more likely to be actively developed.

Here are the links:

This branch:

- https://github.com/digitalheir/latex-parser
- https://github.com/ORCID/bibtexParseJs
- https://github.com/digitalheir/latex-to-unicode-converter

17.09:

- https://github.com/mayanklahiri/bib2json

The complexity of three moving parts vs one (admittedly less actively developed) library weighs a bit on me here (while the change we made didn't make it npm - it did make it to the library itself so it wasn't completely dead). 

So I guess I wouldn't have made the same set of choices regarding citations - but I do see the possibility for some real upsides this way. I hope this path works out well - if this is something we decide to really care about it seems we have the possibility of contributing to more active communities this way - and that is important.

**Comment by dannon** [comment]
@jmchilton thanks for taking a look at the bibtex stuff, specifically, even though that turned out to be the smallest part of this PR, heh.  My thinking was that the unicode handling and flexibility were the big wins.   I actually didn't even notice publisher had been dropped, and bet I can fix that along with the italics in a subsequent PR because the libraries I picked here are much more modern and easier to extend and work with.   A good example is the error handling; Instead of just mangling `({\noopsort{1973b}}1973)`, with the libraries I've used here we can actually handle that unknown command and return whatever we'd like (in this case, I've returned the raw bibtex, though we can change that of course).

I'll work on tweaking the italics and publisher handling for a subsequent PR; we can definitely get that working better before 18.01.

**Comment by anuprulez** [comment]
@dannon I pulled this branch and tried to create a workflow but could not in Mozilla (57.0 (64-bit)) as well as in Chrome (Version 62.0.3202.89). I am able to open individual tools but not able to add any to a workflow. I cloned the codebase from:

`git clone https://github.com/dannon/galaxy --branch bibtex-replacement-lib`

and it is up to date. Please ignore if you can create a workflow or this issue is unrelated. Thank you!

Mozilla:

moz


Chrome:

chr

Update: Now I am doing `make client` and would check again. I did not do it before. Let's see...

**Comment by dannon** [comment]
@anuprulez I had left out a bit of the refactoring related to the workflow globals handling, thanks!  Works for me with the latest change.

**Comment by jxtx** [comment]
So, this is basically the opposite of addressing @jmchilton 's concern about complexity and additional libraries, but rather than making a comprehensive bib renderer ourselves can we use citation-js or something similar that uses the citation style language standard?

**Comment by jmchilton** [comment]
Just to clarify - I was opposed to adding additional dependencies without getting some clear benefit. Not actually building a bibtex renderer ourselves would be a huge benefit (see commit message [here](https://github.com/galaxyproject/galaxy/commit/a7f59b24bef57ca7300787db994598bf75ee3bbc) for instance).

**Comment by jxtx** [comment]
Fair enough! Let's get out of this game.

**Comment by jmchilton** [comment]
> Let's get out of this game.

... as part of a subsequent PR so we don't block Vue even further on the citations point... right @jxtx?

**Comment by jxtx** [comment]
Mais oui!

**Comment by martenson** [comment]
1. There is a horizontal gap before the citation is shown.

screenshot 2017-11-21 11 56 59

2. Also the 'cite us' text is new, right? I am not a fan (it is probably not for me to decide though), however due to its color it is the most eye-catching thing on the whole toolform page which I see as problematic.

3. Can we get rid of the console logs from vue? Also it seems we need to adjust the release process to accommodate for [switching](https://vuejs.org/v2/guide/deployment.html) vue to production.

```
vue.js:8260 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools

12:07:28.891 vue.js:8270 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
12:07:29.195 
```
4. the [vue devtools](https://github.com/vuejs/vue-devtools) do not seem to work with our vue (probably not a problem)

5. after running `make client` on this branch I have a ~~change in~~ untracked file `static/scripts/libs/bibtex.js`

6. after clicking 'visualize in charts' on a dataset:

```
Uncaught TypeError: Utils.get is not a function
    at app.js:12
    at Object.execCb (require.js?v=1511280824:1)
    at b.check (require.js?v=1511280824:1)
    at b.<anonymous> (require.js?v=1511280824:1)
    at require.js?v=1511280824:1
    at require.js?v=1511280824:1
    at each (require.js?v=1511280824:1)
    at b.emit (require.js?v=1511280824:1)
    at b.check (require.js?v=1511280824:1)
    at b.enable (require.js?v=1511280824:1)
```

File: client/galaxy/scripts/apps/analysis.js [hunk 5]
```diff
@@ -119,6 +122,13 @@ window.app = function app(options, bootstrapped) {
             this.page.display(new HistoryList.View({ action_id: action_id }));
         },
 
+        show_history_citations: function() {
+            var citationInstance = Vue.extend(Citations);
+            var vm = document.createElement("div");
+            this.page.display(vm);
+            new citationInstance({ propsData: { id: QueryStringParsing.get("id"), source: "histories" } }).$mount(vm);
```
Comment (martenson) [inline client/galaxy/scripts/apps/analysis.js:129]: this spacing seems to be different from our standard

**Comment by jmchilton** [comment]
The cite is text used to only be in the history wide view - where it looks better and makes more sense IMO. There you are summarizing a whole analysis and would expect many more citations and aren’t trying to take focus away from the tool. I wouldn’t include it in the tool form this way - I agree completely.

**Comment by dannon** [comment]
Yeah, the text isn't new, but it seemed like a good idea this morning to standardize the (now trimmed down) info message.  Seems less like a good idea in retrospect; I'll add the toggle back in.

**Comment by dannon** [comment]
Ok.
- Popped the message back off the toolform; only shows in the 'history citations' view, adjusted the structure slightly.
- Vue debug text will go away after more work building an actual production bundle at release time, probably not 18.01
- Vue devtools are working fine for me in firefox, not sure what's up on your end there.
- The bibtex.js file is because of a (now) untracked previously bibtex.js in your client libs.
- looking at charts now...

**Comment by dannon** [comment]
The charts issue is unrelated to this PR (broken in current -dev).  I'll follow up with a fix separately.

File: client/galaxy/scripts/apps/analysis.js (hunk 5 above)
Comment (dannon) [reply client/galaxy/scripts/apps/analysis.js:129]: It is whatever client-format did.

**Comment by martenson** [comment]
@dannon ad charts: I did only check against 17.09, we are fast in breaking! :)

**Comment by dannon** [comment]
@martenson Yeah, it's related to the *other* massive client changes we already did this cycle :)

File: client/galaxy/scripts/apps/analysis.js (hunk 5 above)
Comment (martenson) [reply client/galaxy/scripts/apps/analysis.js:129]: I thought we abandoned extra spaces with regards to parens.

**Comment by anatskiy** [comment]
Great work! I didn't notice any issues :)
