### PR TITLE
[26.0] Various fixes to file source template's validation system

### LINKED ISSUE #21668: Problems with file source form validators
**Describe the bug**

I was playing around with validators in file source templates  https://github.com/galaxyproject/galaxy/pull/21155 

- When loading the form the validator of the first input (Name) runs and reports the that it does not validate (because it's empty on load), but the remaining fields are apparently not validated. After filling a name I can submit the form despite validators would fail for other fields. 
- I tried to add a `length` validator. But it seems that the validator does not run when the field is empty (only if I add characters .. also if I clean the field the validator seems not run)
- should [this](https://github.com/davelopez/galaxy/blob/0f8aa5fdfe0d184f6b501b6413058514254551f2/client/src/components/Form/utilities.js#L167) check against `!= null` instead of `!== undefined`? 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 25.1 + https://github.com/galaxyproject/galaxy/pull/21155 

**Expected behavior**

- all fields are validated on load
- changed field is validated

### PR DESCRIPTION
**Pull request by davelopez**
Fixes #21668

While investigating #21668 I discovered several issues with file source templates validation and **form validation in general**.
- In templates, there was no way to tell if a variable or secret was required or optional. I'm not sure if this was intentional, but all template variable models (`TemplateVariableString`, `TemplateVariableInteger`, `TemplateVariableBoolean`) had a hardcoded default that made them allways optional by definition. Also, the `optional` field was not set in the UI for any of these fields, so the form couldn't tell if they were actually optional or not, which made it confusing for the user.
  | Before | After |
  |--------|-------|
  |  image  | image |
  | image   | image  |

- <del>There were also a couple of conditions in form validation in general that seem wrong. For example, in https://github.com/galaxyproject/galaxy/pull/21704/changes/2fad152fcebb401087087457facf4d4325dae377, having `(allowEmptyValueOnRequiredInput && inputValue === "")` resulted in a validation error, which, according to the name of `allowEmptyValueOnRequiredInput`, should be completely the opposite. Also in https://github.com/galaxyproject/galaxy/pull/21704/changes/49b3cab74f4079229027e922f1c18cbd7cf4dd57, the `!isRequired` condition seemed to be wrong.</del> The logic was correct, but the `allowEmptyValueOnRequiredInput` flag really means `rejectEmptyRequiredInputs` and will be renamed in dev here https://github.com/galaxyproject/galaxy/pull/21775
- Another issue was that `validateInputs` was only validating some inputs and not all of them. For example, if we provide the required name of file source, and then clear the field, the validation will pass because we were checking only "provided" values for validation and not all input definitions. See https://github.com/galaxyproject/galaxy/pull/21704/changes/3fa5bd0dab67df31858cdb68acc06c3019ed78c4.
- The "create" button was always enabled, even when validation issues were still present.

  | Before | After |
  |--------|-------|
  | image   | image  |

I've updated the templates to include optional values when appropriate, and I increased the test coverage to account for possible optional values.

## How Validation Works now in templates according to "optionality"

- Variables and secrets are **required by default**.
- A variable or secret is optional **only if** `optional: true` is explicitly set.
- Defining a `default` value **does not** make a field optional.
- Default values are applied **only** for variables or secrets marked as `optional: true`.
- Validators are evaluated **only when a value is provided**; omitted optional fields are not validated.
- Default values **are validated** when they are applied (i.e. for `optional: true` fields with a default).

**Frontend Behavior:**
- Iterates over field definitions (not just provided values) to catch missing required fields
- The first validation issue found stops the iteration and displays the error, and as soon as it is fixed, the next validation error is shown. This was the same before, but the additional field validation was skipped due to all fields being considered optional.
- Real-time validation feedback with error messages
- Submit button is disabled when validation errors exist

## How to test the changes?
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:
  - Enable any of the file source templates in `config/file_source_templates.yml`
  - Play around with the `optional`, `default`, and `validators` fields in the templates
  - Restart Galaxy to pick up the template changes
  - Go to your User settings and try to create any of the file sources with those tweaks
  - Check that the validation and optionality work as expected

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by mvdbeek** [comment]
I can't quite tell if this logic is re-used in tools or workflows, so if it isn't reused you can ignore this:

> * A field is **optional** if it has an explicit `default` value (e.g., `""`, `0`, `false`) _defined in the template_

that doesn't cover the case of a default value that you can choose to delete ... maybe that makes sense for templates but it wouldn't for tools or workflows.

Can we work with an explicit field to make things optional or required ? This is how tools handle optionality (even if we do derive some defaults based on the default value and parameter type)

> Required fields: Always validated - must have a non-empty value

Again, that may make sense for file source templates but empty string should satisfy this requirement for tools and workflow, as opposed to null.

> Optional fields (empty): Validation skipped - defaults are used

This seems surprising ? You'd want to validate everything, no ? What if the value is `CHANGE_ME!!!` ?


I suppose the lesson we're learning over and over again is that not everything is a tool form 😅.

**Comment by davelopez** [comment]
> Can we work with an explicit field to make things optional or required ? This is how tools handle optionality (even if we do derive some defaults based on the default value and parameter type)

Yes, this also feels better to me. I wanted to fix the existing behavior without adding new syntax to the templates, but this is probably justified for a fix.

> >Required fields: Always validated - must have a non-empty value

> Again, that may make sense for file source templates but empty string should satisfy this requirement for tools and workflow, as opposed to null.

This can probably be avoided by having the explicit "optional" in the template, so one more point in favor.

> > Optional fields (empty): Validation skipped - defaults are used

> This seems surprising ? You'd want to validate everything, no ? What if the value is CHANGE_ME!!! ?

Hah! :laughing:  I didn't consider that, I expected default values to be valid and sensible. But I guess it makes sense to be more consistent here just in case.

> I suppose the lesson we're learning over and over again is that not everything is a tool form 😅.

Why not? Once you have a hammer... :laughing: 

Thanks so much for the feedback! I will try to make the optional explicit and see where we get from there.

File: client/src/components/Form/utilities.js [hunk 1]
```diff
@@ -208,21 +210,24 @@ function runValidator(validator, value) {
...
         if (!inputDef || inputDef.step_linked) {
             continue;
         }
-        if (!inputDef.optional && inputDef.type != "hidden") {
-            if (inputValue == null || (allowEmptyValueOnRequiredInput && inputValue === "")) {
+        if (isRequired && inputDef.type != "hidden") {
+            if (isEmpty && !allowEmptyValueOnRequiredInput) {
                 return [inputId, "Please provide a value for this option."];
             }
         }
```
Comment (davelopez) [inline client/src/components/Form/utilities.js:226]: I think this change around `allowEmptyValueOnRequiredInput` is breaking how the workflow form handles the Run button disabled logic.
```
FAILED lib/galaxy_test/selenium/test_workflow_run.py::TestWorkflowRun::test_workflow_run_button_disabled_when_required_input_missing - selenium.common.exceptions.TimeoutException: Message: Timeout waiting on CSS selector [#run-workflow.g-disabled] to become present.
```
But I think the previous logic was incorrect or, at least, it reads backwards to me.
With the previous logic, the validation error was returned `if the inputValue **was empty** AND **allowEmptyValueOnRequiredInput was true**`.
The new logic reads correctly to me, if the input value is empty and we DON'T allow empty values on required inputs... then the validation should fail.

Am I missing something? 🤔

Comment (davelopez) [reply client/src/components/Form/utilities.js:226]: I will change this back and assume `allowEmptyValueOnRequiredInput` in really `rejectEmptyRequiredInputs` as discussed here https://github.com/galaxyproject/galaxy/pull/21775#discussion_r2782545536

**Comment by davelopez** [comment]
This one is finally ready for review! All the remaining test failures are unrelated

**Comment by davelopez** [comment]
Thank you, Marius!
