### PR TITLE
[26.0] Fix TypeError in ExternalIdentities by always including provider_label in authnz response

### LINKED ISSUE #22230: TypeError: Cannot read properties of undefined (reading 'trim')
Sentry Issue: [GALAXY-MAIN-4KSCZZZ0014PS](https://sentry.galaxyproject.org/organizations/galaxy/issues/292490/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'trim')
  at VA (/static/dist/analysis.bundled.js:228:1530)
  at s.capitalizeAsTitle (/static/dist/analysis.bundled.js:250:943)
  at None (/static/dist/analysis.bundled.js:262:33)
  at s.Jue [as _l] (/static/dist/galaxy-app-BE2IGCRj.js:1:15120)
  at s.PIn (/static/dist/analysis.bundled.js:261:187)
...
(7 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by guerler**
Resolves #22230.

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/utils/strings.ts [hunk 1]
```diff
@@ -46,6 +46,9 @@ export function snakeCaseToTitleCase(str: string): string {
  * Capitalize the first letter of a string
  */
 export function capitalizeFirstLetter(str: string): string {
+    if (!str) {
+        return "";
+    }
```
Comment (mvdbeek) [inline client/src/utils/strings.ts:51]: That seems like an unnecessary guard for an empty string, `"".trim().charAt(0).toUpperCase()+"".slice(1)` would work fine. If you widen the type the `str?: string` that would make more sense to me?

**Review by mvdbeek — APPROVED** [review]
