### PR TITLE
[24.1] Fix alert handling in workflow label handler

### LINKED ISSUE #18801: Workflow Editor required inputs should remove warning indicator when populated
image

We have the exclamation icon and the `Add a step label` warning even when the fields are populated. Maybe this needs a rework?

### PR DESCRIPTION
**Pull request by guerler**
Fixes #18801. The label input field is already a standalone input element, there are no structural issues. This issue was likely caused while switching to TypeScript.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/Form/FormElement.vue [hunk 1]
```diff
@@ -177,7 +177,7 @@ const isOptional = computed(() => !isRequired.value && attrs.value["optional"] !
 const formAlert = ref<string>();
 const alerts = computed(() => {
     return [formAlert.value, props.error, props.warning]
-        .filter((v) => v !== undefined && v !== null)
+        .filter((v) => v !== undefined && v !== null && v !== "")
```
Comment (mvdbeek) [inline client/src/components/Form/FormElement.vue]: Why is there an empty string in one of the array elements ? Isn't that would should be fixed ?

Comment (guerler) [reply client/src/components/Form/FormElement.vue]: It is returned in: https://github.com/galaxyproject/galaxy/blob/dev/client/src/components/Workflow/Editor/composables/useUniqueLabelError.ts#L13

Comment (mvdbeek) [reply client/src/components/Form/FormElement.vue]: Can you change the ref to `const error = ref<string? | null>();` instead and then set error.value to `null` if there's no duplicate label ?

**Review by mvdbeek — APPROVED** [review]
Final thing, can you target 24.1 ?
