### PR TITLE
[23.0] Fix API key reveals on mouse hover

### LINKED ISSUE #17936: Do not show API key on mouse over?
**Describe the bug**

Was wondering if it's a good idea to show the API key in the user preferences simply on mouseover. Maybe a click would be better (or even confirmation dialog).

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0

**Browser and Operating System**
Browser: Firefox

### PR DESCRIPTION
**Pull request by itisAliRH**
Close #17936

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by davelopez — COMMENTED** [review]
Since this is a bug fix, can you retarget to the 23.0 release branch where this was implemented? :)

**Comment by itisAliRH** [comment]
Failed tests are irrelevant.

File: client/src/components/User/APIKey/APIKeyItem.vue [hunk 1]
```diff
@@ -59,6 +59,11 @@ const deleteKey = () => {
                                 :text="item.key"
                                 title="Copy key" />
                         </b-input-group-text>
+
+                        <b-button v-b-tooltip.hover title="Show/hide key" @click="hover = !hover">
```
Comment (davelopez) [inline client/src/components/User/APIKey/APIKeyItem.vue:63]: Reaaaally nitpicking... but how about renaming `hover` to `reveal` or something similar? :)

**Review by davelopez — APPROVED** [review]
