### PR TITLE
Fix GTabs vertical layout and spacing

### LINKED ISSUE #21966: GTabs (vertical): Layout and spacing broken
**Describe the bug**
This appears to be a regression introduced in #21960:
|Expected (before)|Now|
|-|-|
|image|image|

### PR DESCRIPTION
**Pull request by dannon**
## Summary

Fixes the broken vertical tab layout introduced in #21960 (GTabs/GTab replacement).

- Container now uses Bootstrap's `row`/`no-gutters` grid instead of plain `d-flex`
- Nav is wrapped in a `col-auto` div for proper column sizing (matching BSV's rendered structure)
- Tab content gets `col` class to fill remaining space
- When `card+vertical`, the nav gets `card-header h-100 border-bottom-0 rounded-0` (matching BSV)
- GTab panes now get `card-body` class when the parent GTabs has the `card` prop, restoring content padding

Fixes #21966

## Test plan

- Verify vertical tabs layout in History → Export History (needs writable file sources configured)
- Verify vertical tabs layout in History → Archive History
- Verify non-vertical tabs are unaffected (e.g. Dataset Attributes, Upload, SanitizeAllow admin page)

### CODE REVIEW

**Comment by nsoranzo** [comment]
Can you maybe also fix:

```
FAILED lib/galaxy_test/selenium/test_admin_app.py::TestAdminApp::test_html_allowlist - selenium.common.exceptions.TimeoutException: Message: Timeout waiting on XPATH selector [//a[contains(text(), "Local Tools")]] to become clickable.
```

which (I think) was  also introduced in https://github.com/galaxyproject/galaxy/pull/21960 ?

**Comment by davelopez** [comment]
I've pushed an update of the navigation.yml selectors that should fix `lib/galaxy_test/selenium/test_admin_app.py::TestAdminApp::test_html_allowlist`. Feel free to drop it if you prefer to change the component to match the existing one instead!

**Comment by dannon** [comment]
Hrmm.  When you looked did you see what didn't match?  Updating the selectors was actually what I had first but then I figured if it was just the span we'd be better off dropping that instead to align the template with the old structure.

I don't mind updating the selectors here, just curious what else threw off the match -- thanks for taking a look!

File: client/src/components/BaseComponents/GTabs.vue [hunk 1]
```diff
@@ -138,28 +145,59 @@ const TabTitleContent = defineComponent({
                 const nodes = props.tab.titleRenderer();
                 return nodes.length === 1 ? nodes[0] : h("span", nodes);
             }
-            return h("span", props.tab.title || "");
+            return props.tab.title || "";
```
Comment (davelopez) [inline client/src/components/BaseComponents/GTabs.vue]: > When you looked did you see what didn't match?

Yes, it was the additional span that was still present. I even tried to remove the one in line 146 just in case, but I was still getting this in the elements inspection panel:

Image

If you can drop the extra span, that will be my preferred option too.

**Review by davelopez — APPROVED** [review]
Thank you!
