### PR TITLE
[18.05] Fix and repack chart tool-based visualizations

### LINKED ISSUE #6043: tool-running charts output error
When I go to 'saved visualizations' to see the output of my charts run I get the spinning wheel with message `Job completed successfully...` and a JS console error

```
script.js:937 Uncaught ReferenceError: Plot is not defined
    at script.js:937
    at Object.success (jobs.js:117)
    at Object.<anonymous> (utils.js:191)
    at l (jquery.js:3187)
    at Object.fireWith [as resolveWith] (jquery.js:3317)
    at i (jquery.js:8757)
    at XMLHttpRequest.<anonymous> (jquery.js:9123)
```

this is the Box plot (jqPlot) tool on Test

### PR DESCRIPTION
**Pull request by guerler**
Fixes #6043. Ping @martenson

### CODE REVIEW

File: config/plugins/visualizations/jqplot/jqplot_bar/src/script.js [hunk 1]
```diff
@@ -1,9 +1,12 @@
-import * as d3 from "d3";
+import * as d3 from 'd3';
 import jqplot from 'jqplot-exported/jqplot';
 import { LineRenderer } from 'jqplot-exported/LineRenderer';
 import { BarRenderer } from 'jqplot-exported/plugins/BarRenderer';
+import { OHLCRenderer } from 'jqplot-exported/plugins/OHLCRenderer';
 import { EnhancedLegendRenderer } from 'jqplot-exported/plugins/EnhancedLegendRenderer';
 
+window.d3 = d3;
```
Comment (dannon) [inline config/plugins/visualizations/jqplot/jqplot_bar/src/script.js]: We shouldn't be doing this from charts -- different charts will potentially use different versions of d3 from both one another and Galaxy.  It's one of the main reasons we implemented bundling.

Comment (guerler) [reply config/plugins/visualizations/jqplot/jqplot_bar/src/script.js]: Yep, this is fallout from rebundling all visualizations forcing newer dependency versions. We use the same here: https://github.com/galaxyproject/galaxy/blob/6006d9bfcad15b4a840594fb8367a6b1a780a3cf/config/plugins/visualizations/heatmap/heatmap_default/src/script.js#L12
I removed both for reasons of best practice but this disables zooming for heatmaps. The zooming for nvd3 visualizations has not been restored yet either, see: #5423.

Comment (dannon) [reply config/plugins/visualizations/jqplot/jqplot_bar/src/script.js]: Thanks for removing it.  When you say "fallout from rebundling all visualizations forcing newer dependency versions", I'm confused, though.  Every visualization should now be able to bundle *exactly* the versions it needs, and this proliferation of window globals is what caused the problem here to start with.  It's kind of a miracle it ever worked.  Let me know if you want help fixing this for the long term, or need any pointers or whatever.

Lastly, do you mind rebasing this branch with the single pack?  Each pack of these charts is a fairly large diff that we have to carry forward forever.

Comment (guerler) [reply config/plugins/visualizations/jqplot/jqplot_bar/src/script.js]: It probably worked because we used to load d3 in a single version into the global namespace. The zooming feature was written with that d3 version and was shared between visualizations. Its likely that it has to be revisited for the newer library version. The same goes for the newer nvd3 version and the heatmap which currently still uses d3-3.

**Comment by martenson** [comment]
Thanks @guerler !
