### PR TITLE
Fix pasting file fails if text starts with `file `

### LINKED ISSUE #15960: Pasting file fails if text starts with `file `
On 23.0, try pasting a `file ` into the upload box. This is being passed on as a URL to the API, so this should be a frontend bug.

Screenshot 2023-04-19 at 16 12 44

### PR DESCRIPTION
**Pull request by ElectronicBlueberry**
Closes  #15960 by appending `://` to the prefixes which identify URIs

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by davelopez — APPROVED** [review]

File: client/src/components/Upload/helpers.js [hunk 1]
```diff
@@ -1,6 +1,15 @@
 export const defaultNewFileName = "New File";
 
-const URI_PREFIXES = ["http", "https", "ftp", "file", "gxfiles", "gximport", "gxuserimport", "gxftp"];
+const URI_PREFIXES = [
+    "http://",
+    "https://",
+    "ftp://",
+    "file://",
```
Comment (hexylena) [inline client/src/components/Upload/helpers.js:7]: we should definitely not allow file:// as a protocol, right? especially not for user facing anything (or is that needed for 'import from path')

Comment (mvdbeek) [reply client/src/components/Upload/helpers.js:7]: That I don't know, but the authoritative check is done on the backend, this just determines what looks like a URL vs what should be assumed is pasted content.

Comment (hexylena) [reply client/src/components/Upload/helpers.js:7]: Ah, fine then, no worries. (I'm pretty sure I checked that when I did the local address filtering, like 7 years ago, so, we're fine)
