### PR TITLE
[24.2] Fix workflowID assignment in Markdown.vue

### LINKED ISSUE #19503: TypeError: undefined is not an object (evaluating 'Object.keys(this.markdownConfig.workflows)')
Sentry Issue: [GALAXY-MAIN-YBB](https://sentry.galaxyproject.org/organizations/galaxy/issues/152667/?referrer=github_integration)

```
TypeError: undefined is not an object (evaluating 'Object.keys(this.markdownConfig.workflows)')
  at We.methods.initConfig (webpack://@galaxyproject/galaxy-client/src/components/Markdown/Markdown.vue:191:42)
  at We.created (webpack://@galaxyproject/galaxy-client/src/components/Markdown/Markdown.vue:174:14)
...
(20 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by davelopez**
Fixes #19503

`this.markdownConfig` might not have `workflows`.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/Markdown/Markdown.vue [hunk 1]
```diff
@@ -188,7 +188,7 @@ export default {
                 this.workflows = config.workflows || {};
                 this.invocations = config.invocations || {};
                 this.loading = false;
-                this.workflowID = Object.keys(this.markdownConfig.workflows)[0];
+                this.workflowID = Object.keys(this.markdownConfig?.workflows ?? {})[0] ?? "";
```
Comment (mvdbeek) [inline client/src/components/Markdown/Markdown.vue]: Should this maybe be undefined ? Also we seem to be calling `fetchWorkflowForInstanceId` and `getStoredWorkflowByInstanceId` with an empty string, that's probably also not quite right ?

Comment (davelopez) [reply client/src/components/Markdown/Markdown.vue]: Yep, I blindly followed what was there as default. I'll fix it :+1:

**Review by mvdbeek — APPROVED** [review]
Thank you!
