### PR TITLE
[21.09] Fix workflow invocation name overflow

### LINKED ISSUE #12857: Text overflows on workflow invocation page
Current on ORG -- longer titles for a workflow overflows involving underscores onto the associated history on the workflow invocation page. Likely not encountered very often, but it's a minor bug.

**To Reproduce**
1. Go to workflow invocation
2. View invocation for workflow with long name connected by underscores

**Expected behavior**
Text should wrap

**Screenshots**
Screen Shot 2021-11-04 at 1 22 43 PM

### PR DESCRIPTION
**Pull request by davelopez**
Fixes #12857

Screenshot from 2022-01-21 12-33-10

- Added back the "expand" column to make it more obvious that the row has additional details and to display the full name as a tooltip when it gets truncated as @itisAliRH suggested. The previous expand button was removed in https://github.com/galaxyproject/galaxy/pull/9986. @guerler I hope adding back this column makes sense now :)

## How to test the changes?
- [x] Instructions for manual testing are as follows:
  - Follow instructions on #12857

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Comment by dannon** [comment]
Thank you @davelopez for taking a stab at this. Now that I see it, though, I'm not sure about breaking on everything (even though I suggested it, sorry).  It makes the following two invocations, which would otherwise break naturally at the word, break unnaturally.  A step nicer might be to inject `<wbr>` tags where we have a set of characters we want to break on?

What do other folks think?

**Comment by bgruening** [comment]
That's maybe a more general feeling/discussion, but I do not like those big rows and rows with unequal height. I would cut the name and show the full name on hover. The other thing is that the width of the other columns are to small and the name column should be broader?

**Comment by nsoranzo** [comment]
`overflow-wrap: break-word;` could be better?

**Comment by dannon** [comment]
@nsoranzo break-word is the default `normal`, and what it would have done before.  The issue here was that the workflow name had underlines in it, so it was one giant 'word'.

**Comment by nsoranzo** [comment]
> (ahh, but now that I look it up-- it's not purely a replacement. we can add `overflow-wrap: anywhere` as well here I think -- see more at https://developer.mozilla.org/en-US/docs/Web/CSS/word-break)

Yes, that's where I found it, but `overflow-wrap: break-word;` looks better to me than `overflow-wrap: anywhere` from the demos at https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

**Comment by dannon** [comment]
@nsoranzo Sorry, I need more coffee apparently.  I read your first comment as `word-break: break-word`, which is indeed deprecated; I didn't see you were talking about the `overflow-wrap` property there.  +1 to swapping to `overflow-wrap: break-word` here.  

I think what @bgruening mentioned is good, too -- instead of even-width columns at least the last 3 should shrink to consume minimal space and the first one (maybe two) should be be larger.

**Comment by davelopez** [comment]
Ok, thanks for the suggestions!
I will try the `overflow-wrap: break-word;` and also tweak a bit the column widths.

**Comment by davelopez** [comment]
After wrestling with CSS more than I would have desired (and discovering `v-deep`) the result is now this:

Screenshot from 2022-01-19 18-34-11

I don't know if this is the best way of setting the table column widths, the other solutions I tried of setting the style inline looked definitely uglier to me.

Also, for some unknown reason, I can not get the `min-width` to work in the first column so if you reduce the available width enough it will wrap into weirdness... :disappointed: 

Screenshot from 2022-01-19 18-44-16

Any hints from CSS experts?

**Comment by itisAliRH** [comment]
I have an idea😁. I prefer the same width rows with one line text and a button at the end to collapse details but change other things. We can make some more space by replacing `state` with icons (but with better icons😅), moving its text on the hover tooltip, adding scroll to name and truncating it with a ... indication, replacing its tooltip with full name, and adding a new column to show details.

Another thing that could be useful is adding a width breakpoint that enables the overflow of the whole table on small screens.

image

**Comment by davelopez** [comment]
Thank you @itisAliRH! those are definitely nice improvements. Probably will be a good idea to revisit all existing tables and unify a bit their look and feel so all of them provide a consistent experience, but since this is a fix for a previous release I prefer to keep the changes small.
I tried the truncated name with an ellipsis (...) here, but still, the min-width issue allows for something like this which is not nice... 

Screenshot from 2022-01-20 11-46-47

Also the tooltip already contains "Show invocation details", so I guess I can change it to "Show invocation details for *full workflow name here*".

**Comment by itisAliRH** [comment]
No problem :). I think you want this:

preview

For this, `min-width` must be added to the `b-table`:
```
.table {
    min-width: 40rem; /*  needed at least 600px */
}
```

and change this:
```
.table::v-deep .col-name {
    width: 40%;
    overflow: auto;
    white-space: nowrap;
}
```

> Also, the tooltip already contains "Show invocation details", so I guess I can change it to "Show invocation details for full workflow name here" or add the nice column to expand the details as you suggested.

Agree with you👍🏻

**Comment by itisAliRH** [comment]
For having ellipsis and overflow scrolling at the same time, I can't find a solution with only CSS to prevent white space.
Please check here: https://codepen.io/itisalirh/pen/JjrQEro
Any idea?

**Comment by davelopez** [comment]
> For this, min-width must be added to the b-table

Thank you so much! that definitely did the trick :)

Now it looks like this in really small resolutions:
Screenshot from 2022-01-21 12-24-26

> For having ellipsis and overflow scrolling at the same time, I can't find a solution with only CSS to prevent white space.

I guess it's fine without the overflow scrolling in the cell that may be too much scrolling going around :smile:

**Comment by nsoranzo** [comment]
Nice! But why is the tooltip over the history name instead of the workflow name?

File: client/src/components/Workflow/Invocations.vue [hunk 1]
```diff
@@ -33,11 +34,27 @@
...
+                        v-if="data.detailsShowing"
+                        @click.stop="swapRowDetails(data)"
+                    />
+                </template>
                 <template v-slot:cell(workflow_id)="data">
                     <b-link
                         class="toggle-invocation-details"
                         v-b-tooltip
-                        title="Show Invocation details"
+                        :title="getWorkflowNameByInstanceId(data.item.workflow_id)"
```
Comment (mvdbeek) [inline client/src/components/Workflow/Invocations.vue:56]: Is the the `toggle-invocation-details` class still right here ? And I guess we should have the same tooltip for the history name, which could also be too large

**Comment by davelopez** [comment]
> Nice! But why is the tooltip over the history name instead of the workflow name?

Good question, I guess tooltips are wild spirits! They appear where they want and they only disappear when they want :laughing: 
Seriously, probably there is a way to control that, but I don't know how right now, any hints?

File: client/src/components/Workflow/Invocations.vue (hunk 1 above)
Comment (davelopez) [reply client/src/components/Workflow/Invocations.vue:56]: Yes, I left the `toggle-invocation-details` class there (is used in tests) and you can still expand the details if you click the name so the previous mechanism is still working for people that are used to it.
I agree the history name column should behave exactly the same and also overflow with ellipsis too instead of wrapping for consistency. Will do that :+1:

Comment (mvdbeek) [reply client/src/components/Workflow/Invocations.vue:56]: Sounds good, but maybe you can move the `toggle-invocation-details` class to the new button ? I do want to add more context to the workflow and history cells anyway (filter by workflow / history for instance), but I can do that in dev

Comment (davelopez) [reply client/src/components/Workflow/Invocations.vue:56]: Ok, I moved the class to the new button but still left the expand row details working on the workflow name, you can remove it on dev if you need it when you add the new stuff.

**Comment by dannon** [comment]
@davelopez Sorry this ended up being a rabbit hole, but I think it was well worth the time spent, this looks great!

**Comment by davelopez** [comment]
No worries! I learned a lot about my new nemesis... CSS :laughing:

**Review by itisAliRH — APPROVED** [review]

**Review by dannon — APPROVED** [review]
