### PR TITLE
Dataset chunking tests (and small fixes)

### LINKED ISSUE #15997: Datatype Chunk Tests
Encountered when checking through https://github.com/galaxyproject/galaxy/pull/15972, it'd be nice to add test coverage verifying shipping of various chunk sizes, making sure no lines are skipped when fetching sequential chunks, etc.  Linked PR is specifically the bam chunked data provider, but tests would be nice to have for generic tabular, too.

get_chunk methods:

- [ ] BamNative https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/binary.py#L607
- [ ] TabularData https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/tabular.py#L145
- [ ] ConnectivityTable https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/tabular.py#L1604

Tests for these could also help a conversion of these display chunk methods over to the more modern data providers as discussed earlier this year, and would be potentially useful when iterating to improve performance as in the linked PR.

### PR DESCRIPTION
**Pull request by jmchilton**
See the commit message on the individual atomic commits.

Fixes #15997

For future John - past you believed the next steps here are:
- Swap the UI to use ``/api/datasets/<id>/display`` instead of ``/dataset/display`` in ``TabularChunkedView.vue``.
- Drop any costume parsing or support for ``offset`` as a parameter in the legacy dataset controller so we can be comfortable everything is coming in through the tested API endpoint.
- If offset is sent to services.Dataset.display  - use a data provider the way show would instead if possible? See if we can mimic the external interface while coalescing around data providers internally. 

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/schema/schema.ts [hunk 1]
```diff
@@ -8498,11 +8498,15 @@ export interface operations {
             /** @description If non-null, get the specified filename from the extra files for this dataset. */
             /** @description The file extension when downloading the display data. Use the value `data` to let the server infer it from the data type. */
             /** @description The query parameter 'raw' should be considered experimental and may be dropped at some point in the future without warning. Generally, data should be processed by its datatype prior to display. */
+            /** @description Set this for datatypes that allow chunked display through the display_data method to enable chunking. This specifies a byte offset into the target dataset's display. */
+            /** @description If offset is set, this recommends a number of chunked lines to output from the display API. This is not respected uniformly and should be interpreted as a recommendation. For instance, with bam datatypes this is ignored for the header lines but the remainder of the file respects this parameter. */
```
Comment (wm75) [inline client/src/schema/schema.ts]: I've been wondering about exactly this definition when I touched the implementation for bam files last time.
While it's true that for BAMs, ck_size is interpreted as the number of lines in a chunk, for TabularData, for example, it seems to have a rather different meaning: it specifies the minimal number of bytes to display, which are then extended up to the next line ending (see https://github.com/galaxyproject/galaxy/blob/923b5363f830b19ea71add72dff45e9eab56a7bd/lib/galaxy/datatypes/tabular.py#L145).

I guess the byte-based ck_size makes more sense, but have been wondering, which one is the intended behavior.
If BAMs are supposed to behave like tabular data, I'd be happy to rewrite this once more.

Comment (jmchilton) [reply client/src/schema/schema.ts]: I pushed an update that explains this situation in a little more detail. I don't find this discrepancy problematic enough to warrant asking you to spend time fixing it but I try not to get hung up on consistency. If it is important to you feel free to pick a consistent definition for this parameter and unify the approaches - or something else like splitting this into ``chunk_size_bytes`` and ``chunk_size_lines``. I don't think this API has an external consumer so I wouldn't worry about backward compatibility as long as the UI works.

File: lib/galaxy/webapps/galaxy/api/datasets.py [hunk 2]
```diff
@@ -108,6 +109,24 @@
...
+    description=(
+        "Set this for datatypes that allow chunked display through the display_data method to enable "
+        "chunking. This specifies a byte offset into the target dataset's display."
+    ),
+)
+
+DisplayChunkSizeQueryParam = Query(
+    default=None,
+    description=(
+        "If offset is set, this recommends 'how large' the next chunk should be. "
```
Comment (bgruening) [inline lib/galaxy/webapps/galaxy/api/datasets.py:123]: Thanks John for adding this!

**Review by bgruening — APPROVED** [review]
