### PR TITLE
Bug fix - allow file drops into PasteData widget.

### LINKED ISSUE #20231: Drag and Drop in the Main Frame
I developed a new seeding component for the rule builder in the modal and everything was working but then I moved it out into the main panel and added an activity because that is the way I assumed we would move. One of the features I added was dragging and dropping files into it but it doesn't work at all in the body - there upload modal is stealing it. So now 25.0 is sort of broken and I have two more features downstream in development that would use this and are hitting the same bug.

https://github.com/user-attachments/assets/d8cdfba5-5952-4de5-849a-81a6508d7374

Disabling dragging and dropping into the component is fine-ish for 25.0 but I would really like to be able to do this - anybody have any preferences about how to work around this? I assume more specific drag and drop components should take preference over the global upload handler.

### PR DESCRIPTION
**Pull request by jmchilton**
Fixes https://github.com/galaxyproject/galaxy/issues/20231.

I still think it was hard to find / indirect - I wish DragAndDropModal.vue had a prominent comment somewhere to point at this but I couldn't a natural place to document it. Maybe in Analysis.vue right before the DragAndDropModal component appears? At any rate - that would be an enhancement - this is the bug fix.

## How to test the changes?
(Select all options that apply)
- [x] Instructions for manual testing are as follows:
  1. Go to localhost:8081/rules , pick either option on the first step of the wizard, pick "Paste Data" on the second step, drop a text file into the resulting textbox.

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/composables/fileDrop.ts [hunk 1]
```diff
@@ -18,11 +18,14 @@ export function useFileDrop(
...
-    function isAnyModalOpen() {
+    /** returns true if any other more specific file drop target is on the screen and should
+     *  supersede the global file drop or if an existing modal is present and should likewise
+     *  take precedent.
+     */
+    function disableGlobalDropTargetTarget() {
         return (
             document.querySelectorAll(".modal.show").length > 0 ||
-            document.querySelectorAll(".workflow-run-form-simple").length > 0
+            document.querySelectorAll(".galaxy-drop-target").length > 0
```
Comment (ElectronicBlueberry) [inline client/src/composables/fileDrop.ts]: Can we rename this so it is clear that is is referring to file drops specifically? We do support other drop targets, such as history items, or plaintext. Maybe a custom attribute like `data-galaxy-file-drop-target`

**Review by ElectronicBlueberry — COMMENTED** [review]
> I wish DragAndDropModal.vue had a prominent comment somewhere to point at this

I think the very top of `DragAndDropModal.vue` would be the best place to put this. If some component is behaving in a way I don't expect, the component itself is the first place I would usually check.

File: client/src/composables/fileDrop.ts (hunk 1 above)
Comment (jmchilton) [reply client/src/composables/fileDrop.ts]: Fair - done.

**Comment by jmchilton** [comment]
> I think the very top of DragAndDropModal.vue would be the best place to put this. If some component is behaving in a way I don't expect, the component itself is the first place I would usually check.

In the abstract I agree but I'm not sure I love it. I added it anyway though with the rebase.

**Review by ElectronicBlueberry — APPROVED** [review]

**Comment by jmchilton** [comment]
Thanks for the PR review and merge!
