### PR TITLE
[24.2] Fix inconsistent tab handling in invocation view

### LINKED ISSUE #19286: Inconsistent Tab handling when running Workflow Invocations
**Describe the bug**
This is just a minor paper-cut.
When a workflow invocation is running, some of the Tabs in the UI don't have the required information to be displayed until the run is complete. In particular `Reports`, `Export`, and `Metrics` all handle this situation differently.

https://github.com/user-attachments/assets/9ab1c1c1-d444-4d9b-9c7c-eebfde4985be

We should agree on a consistent way to represent that the tab requires the workflow run to finish before it can display useful information.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.2
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**Browser and Operating System**
Operating System: Windows, Linux, macOS
Browser: Firefox, Chrome, Chrome-based, Safari

**To Reproduce**
1. Run any workflow
2. While the workflow is still running, try to check all the tabs in the invocation run.
3. Observe they all behave differently

**Expected behavior**
All tabs should indicate that the information is not yet available in the same way.

### PR DESCRIPTION
**Pull request by ahmedhamidawan**
Fixes https://github.com/galaxyproject/galaxy/issues/19286

https://github.com/user-attachments/assets/d764ad10-90ef-4596-b992-7544622b6457

<details>
<summary><i>Initial (outdated) change, with the added badge to the export tab</i></summary>

https://github.com/user-attachments/assets/8f675a57-7882-435e-bd79-e077c20b26aa

</details>

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/WorkflowInvocationState/WorkflowInvocationMetrics.vue [hunk 1]
```diff
@@ -380,6 +384,10 @@ const groupByInTitles = computed(() => {
 
 <template>
     <div>
+        <BAlert v-if="!props.terminal" variant="warning" show>
+            <LoadingSpan
+                message="The workflow might still be running. Metrics will update and change as the workflow progresses." />
```
Comment (mvdbeek) [inline client/src/components/WorkflowInvocationState/WorkflowInvocationMetrics.vue]:
```suggestion
                message="Metrics will update and change as the workflow progresses." />
```
?

**Review by mvdbeek — APPROVED** [review]
nice!

**Comment by mvdbeek** [comment]
looks like a round of prettier is needed

File: client/src/components/WorkflowInvocationState/WorkflowInvocationState.vue [hunk 2]
```diff
@@ -333,24 +333,36 @@ async function onCancel() {
...
+                        <FontAwesomeIcon :icon="faExclamation" />
+                    </BBadge>
+                </template>
                 <div v-if="invocationAndJobTerminal">
-                    <WorkflowInvocationExportOptions :invocation-id="invocation.id" />
+                    <WorkflowInvocationExportOptions
+                        :invocation-id="invocation.id"
+                        :terminal="invocationAndJobTerminal" />
                 </div>
                 <BAlert v-else variant="info" show>
```
Comment (davelopez) [inline client/src/components/WorkflowInvocationState/WorkflowInvocationState.vue]: I guess this is not used anymore...

**Review by davelopez — APPROVED** [review]
Thanks for the unification!

I personally think that the exclamation badge and disabling the tab is a bit confusing.
For these reasons:
- It draws a lot of attention "for a normal situation" and makes me think there is a problem in those tabs until I read the tooltip.
- The visual state for a disabled tab is not very noticeable (besides for the extra exclamation badge) and requires extra code and style.

Those are not meant to be a -1, just my subjective opinion on UX :sweat_smile:

File: client/src/components/WorkflowInvocationState/WorkflowInvocationState.vue (hunk 2 above)
Comment (ahmedhamidawan) [reply client/src/components/WorkflowInvocationState/WorkflowInvocationState.vue]: oh that's weird, my change initially was 
```
<WorkflowInvocationMetrics :invocation-id="invocation.id" :terminal="invocationAndJobTerminal" />
```

but i think the rebase messed it up 🤯 🤔 😩

Comment (davelopez) [reply client/src/components/WorkflowInvocationState/WorkflowInvocationState.vue]: Yup, the lines are off now :laughing: 
But I was referring to the `<LoadingSpan message="Waiting to complete invocation" />`. It is not needed anymore since you cannot access the tab when the invocation has not finished.

**Comment by ahmedhamidawan** [comment]
image

@davelopez @mvdbeek and folks in general, is this better?

**Comment by mvdbeek** [comment]
Still looks good to me, I think the primary variant is more appopriate ?

**Comment by davelopez** [comment]
Yes, this looks way better to me! Thank you!

**Comment by jmchilton** [comment]
This is a very beautiful enhancement. So much polish!

**Review by jmchilton — APPROVED** [review]

**Review by davelopez — APPROVED** [review]
Thank you! :pray:
