### PR TITLE
[23.0] Rework collapsible FormCard handling; 

### LINKED ISSUE #15363: Hidden Tool Sections have two Keyboard Targets
A hidden tool section has two targets focus-able by keyboard, which both do the same thing.

**To Reproduce**
1. Open tool "Scatterplot with ggplot2"
2. Navigate onto the eye icon of the "Advanced options" section using keyboard
3. Press enter to open it
4. Navigate one further
5. Press enter to close the section again

**Expected behavior**
Only one of the elements is keyboard selectable, since their purpose overlaps.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by dannon**
Fixes #15363.  Reworks collapsible formcard title handling.  Still shows an icon for a clear state display but the whole card header is clickable and keyboard navigable now so it works like our ContentItem expansion.  In doing this I took the 'eye' collapse state icon out of a button so it looks different from other 'operations' that show up in this space in other contexts.  We probably want to consider (in dev) swapping this from the eye to a more standard collapsed/expanded arrowdown/arrowup or the like.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/Form/FormCard.vue [hunk 1]
```diff
@@ -69,7 +62,20 @@ export default {
     data() {
         return {};
     },
+    computed: {
+        portletHeaderClasses() {
+            return {
+                "portlet-header": true,
+                "cursor-pointer": this.collapsible,
```
Comment (guerler) [inline client/src/components/Form/FormCard.vue:69]: Thanks for fixing this accessibility issue. It works much better now. Maybe we should add a scoped class here and set the brand/link text color and hover text-decoration of collapsible section titles to indicate that they can be clicked on.

Comment (dannon) [reply client/src/components/Form/FormCard.vue:69]: I actually dropped the title distinction intentionally since it's not specifically clickable (but the whole header is) to align more with how contentitems work -- do you think we need more than the icon and pointer to signify it expands?  Maybe just swapping the icon to an up/down chevron, instead of an eye?

Comment (guerler) [reply client/src/components/Form/FormCard.vue:69]: I think so, so basically still display the title styled as link, but this can be done in a follow-up when the icon is switched to the chevron in dev. Thanks again for fixing this.

**Review by guerler — APPROVED** [review]

File: client/src/components/Form/FormCard.vue (hunk 1 above)
Comment (dannon) [reply client/src/components/Form/FormCard.vue:69]: Cool, I'll follow up with some options in dev.  Thanks!
