### PR TITLE
Initialize error attribute in input model for workflows

### LINKED ISSUE #13234: Workflow run form validation highlighting broken
**Describe the bug**
The advanced workflow run form doesn't highlight validation errors anymore
Screenshot 2022-01-24 at 18 05 56

(And the new one submits, leading to a broken invocation)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: 64d395862e0b9fb391d4e832abd8e63b82777d35 / dev

**To Reproduce**
1. Create a workflow with a required data input
2. Click submit
3. See that nothing happens

**Expected behavior**

We should highlight the step and display in blue (or was it red ?) that something needs to be fixed.
This still works on 21.09

### PR DESCRIPTION
**Pull request by guerler**
Fixes #13234. Thanks a lot for looking into it @davelopez, your thread was very helpful in narrowing this down. The underlying issue is that the `error` attribute was not initialized correctly and therefore was not consistently reactive.

## How to test the changes?
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by jmchilton — APPROVED** [review]

File: client/src/components/Form/FormDisplay.vue [hunk 1]
```diff
@@ -146,6 +145,9 @@ export default {
             this.onChange(true);
         },
         onCloneInputs() {
+            visitInputs(this.inputs, (input) => {
+                input.error = null;
```
Comment (mvdbeek) [inline client/src/components/Form/FormDisplay.vue]: Hard to tell from here, are you sure you're not mutating the inputs prop here ? I don't see any obvious cloning / deepcopy in visitInputs, but I may be missing something.

Comment (guerler) [reply client/src/components/Form/FormDisplay.vue]: You are right, we can avoid adding the `error` attribute upfront to each input object in the incoming inputs array and instead add them to the local clone only, using `Vue.set`. Thank you.

**Comment by guerler** [comment]
Thank you guys for the review.
