### PR TITLE
[23.1] Fix webhook release note seen pin

### LINKED ISSUE #16375: release notes bullhorn is blinking on every visit
Every page reload resets the blinking so our use of localstorage for state persistence seems to not work correctly.

xref https://github.com/galaxyproject/galaxy/pull/16049

### PR DESCRIPTION
**Pull request by dannon**
Fixes #16375 

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: config/plugins/webhooks/news/script.js [hunk 1]
```diff
@@ -50,24 +50,27 @@
...
-
-        const releaseNotes = `https://docs.galaxyproject.org/en/latest/releases/${currentGalaxyVersion}_announce_user.html`;
         const lastSeenVersion = window.localStorage.getItem("galaxy-news-seen-release");
-        // Check that they've seen the current version's release notes.
-        if (lastSeenVersion != currentGalaxyVersion) {
+
+        // If we're at a deployed release candidate, just mark it seen and show
+        // the previous notes if someone clicks the link.  RC notes won't exist.
+        if (Galaxy.config.version_minor.startsWith("rc")) {
+            // If we, for whatever reason, need to do this again just add
```
Comment (mvdbeek) [inline config/plugins/webhooks/news/script.js:58]: I guess we should have broken this down into major, minor, micro and suffix, or just return the complete version ... whatever is going to replace the webhook is likely also going to have to deal with this ?

**Review by mvdbeek — APPROVED** [review]

File: config/plugins/webhooks/news/script.js (hunk 1 above)
Comment (dannon) [reply config/plugins/webhooks/news/script.js:58]: So moving forward I expect it'll just be an explicit helper script or a button in the admin notifications UI to 'send release notification' that an admin will be able to get hands on and customize prior to sending.
