### PR TITLE
[24.1] Fix multi select clipping in some places

### LINKED ISSUE #19278: UI drop-down menu odd
**Describe the bug**
UI drop-down menu can lose datasets if the drop-down has too many things in it.

**To Reproduce**
1. Go to usegalaxy.eu or usegalaxy.org.au
2. Try to run any tool with a drop-down menu where you have a lot of options in your history
3. See error
Screenshot 2024-12-06 at 12 54 25

**Expected behavior**
The scroll bar can sometimes get lost if it is too high / too low

**Additional context**
Reported by new user at Galaxy SPOC Co-Fest, and verified by two others.

### PR DESCRIPTION
**Pull request by davelopez**
Fixes #19278

| Before | After |
|--------|-------|
| image | image  |

It also fixes the dialogs for bulk changing the datatype and database key in history datasets:

| Before | After |
|--------|-------|
| image   | image  |

## How to test the changes?
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:
  - Follow the steps in #19278
  - Or try to change the datatype of a "batch/bulk" selection in your history.

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/History/CurrentHistory/HistoryOperations/SelectionOperations.vue [hunk 1]
```diff
@@ -402,5 +402,6 @@ export default {
 <style>
 .modal-with-selector {
     overflow: initial;
+    height: 300px; /* To make room for the selector */
```
Comment (dannon) [inline client/src/components/History/CurrentHistory/HistoryOperations/SelectionOperations.vue]: This doesn't ever grow larger than 300, does it?  (i.e., should this be `min-height`?)

Comment (davelopez) [reply client/src/components/History/CurrentHistory/HistoryOperations/SelectionOperations.vue]: Sorry for the late reply. I tried with min-height, but it doesn't change anything since these 2 modals only have the selector and nothing else and they don't grow larger even if you open the dropdown. I will use min-height anyway :+1:

Comment (dannon) [reply client/src/components/History/CurrentHistory/HistoryOperations/SelectionOperations.vue]: No worries, I wasn't asking for any changes really—just curious about that idea. Thanks for the quick fix and followup; it looks great!

**Review by dannon — APPROVED** [review]
