### PR TITLE
[25.0] Fix selection issue when adding tags to workflows in bulk

### LINKED ISSUE #20234: unintuitive tag creation - release testing 25.0
Feedback for release-testing-25.0 concerning the PR: https://github.com/galaxyproject/galaxy/pull/19336

**Describe the bug**
When adding tags for a workflow, clicking on the + symbol closes the tab.
Also, clicking on the name of the tag closes the dropdown menu. no tag is added.
Only if I add new text and click enter, it works
I am not sure if this was intended, but it is very unintuitive for me.

**Galaxy Version 25.0 Test server*

**Browser and Operating System**
Operating System: Linux
Browser: Firefox

**To Reproduce**
1. Go to 'Workflows'
2. Select WF
3. Go to Add tags
4. enter a tag text
5. click on a tag

**Expected behavior**
Instead, I expected a tag to be created as it was when I typed text and pressed enter.

### PR DESCRIPTION
**Pull request by davelopez**
Fixes #20234

https://github.com/user-attachments/assets/7478122f-7b28-4122-aaa2-a1406b835d15

## How to test the changes?
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by davelopez** [comment]
Thank you, @ElectronicBlueberry, for resolving the issue with the dropdown display inside the dialog!

**Comment by davelopez** [comment]
The remaining test failures are unrelated

File: client/src/components/TagsMultiselect/HeadlessMultiselect.vue [hunk 1]
```diff
@@ -266,13 +267,26 @@ watch(
...
+function getPopupLayerId() {
+    try {
+        assertDefined(root.value);
+        const popupLayerRootElement = root.value.closest("dialog, #app");
+        assertDefined(popupLayerRootElement);
+        return popupLayerRootElement.id;
+    } catch (e) {
+        // Fallback to the app layer if no dialog is found
+        return "app";
+    }
```
Comment (ElectronicBlueberry) [inline client/src/components/TagsMultiselect/HeadlessMultiselect.vue]:
```suggestion
    if (root.value) {
        const closestDialog = root.value.closest("dialog");
        return closestDialog.id ?? "app";
    } else {
        return "app";
    }
```

if we just catch the error state, without addressing it, a conditional is cleaner.

Comment (davelopez) [reply client/src/components/TagsMultiselect/HeadlessMultiselect.vue]: Unfortunately, that broke the test again :sweat: 

https://github.com/galaxyproject/galaxy/actions/runs/15348141093/job/43189208083?pr=20362#step:7:21686

Comment (davelopez) [reply client/src/components/TagsMultiselect/HeadlessMultiselect.vue]: Never mind, it was missing an optional chaining, it should be good now :+1:

**Review by ElectronicBlueberry — APPROVED** [review]
