### PR TITLE
[24.1] Fix workflow tags initialisation in workflow editor

### LINKED ISSUE #18394: Workflow Editor removes tags on save
When you open the editor for a workflow with tags, they do not show up and if you make changes and save, the tags are removed.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: usegalaxy.org (`release_24.1`)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Add a tag to a workflow in the workflows list
2. Click on 'Edit'
3. See that the tags are not populated in the right panel
4. Make a minor change and save
5. Return to the workflows list and note that the tag you added is no longer present

**Expected behavior**
Tags should be populated on workflow editor load.

**Screenshots**

https://github.com/galaxyproject/galaxy/assets/78516064/96cc01ee-0ad7-4b81-a4a8-48d4a506cc4c

### PR DESCRIPTION
**Pull request by itisAliRH**
Fixes #18394 

https://github.com/galaxyproject/galaxy/assets/8046843/d6d15e11-0b01-42bc-a98e-eb13be944da1

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/Workflow/Editor/Index.vue [hunk 1]
```diff
@@ -354,7 +354,7 @@ export default {
             }
         }
 
-        const tags = ref([]);
+        const tags = ref(props.workflowTags);
```
Comment (mvdbeek) [inline client/src/components/Workflow/Editor/Index.vue]: I think you'll be mutating the prop in https://github.com/galaxyproject/galaxy/blob/55439e455e81b7e900b21d4926495ac4abb58ac9/client/src/components/Workflow/Editor/Index.vue#L360.

```suggestion
        const tags = ref([...props.workflowTags]);
```
might work maybe ? I didn't test that but I think that shouldn't mutate the prop ?

Comment (itisAliRH) [reply client/src/components/Workflow/Editor/Index.vue]: Both work but I can't see any difference here. BTW, I made the changes to prevent future issues.

Comment (ElectronicBlueberry) [reply client/src/components/Workflow/Editor/Index.vue]: The linked line does not mutate the prop, since it overwrites the entire array, not its contents.

While initialisation of a ref via a prop does work, it breaks reactivity for the prop. This is currently a problem for multiple parts of the workflow editor, but it would be nice if we could get rid of them bit by bit. In order to initialise a ref with a prop, set it via a watcher set to immediate. That way when the prop changes from a parent component, the ref is also updated.

**Review by mvdbeek — APPROVED** [review]
