### PR TITLE
[24.2] Fix duplicate entries when using drag and drop in multiple mode

### LINKED ISSUE #19803: Data param allows selection of the same dataset twice
**Describe the bug**
The dropdown dataset selection (not the column select) allows the same dataset to be selected twice for a single parameter. It happens only when a user double clicks on the dataset while selecting. I guess this should not be allowed. If I remember correctly, when a dataset was already selected from the dropdown, it would disappear from the dropdown. But in the latest version, the selected datasets still appear in the dropdown. 

- The first screenshot shows that the dataset 4 was selected twice. 
- The second screenshot shows that the dataset 5 was selected as count file but still shown in the dropdown.

**Screenshots**

Image

-------------------------------------------------------------------------------------------------------------------------------

Image

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: `{"version_major":"24.2","version_minor":"2.dev0"}` on usegalaxy.eu

**Browser and Operating System**
Operating Systems: Ubuntu, Windows
Browser: Chrome, Firefox

**Galaxy History with error**
We observed this yesterday during a workshop. We could find it because luckily DESeq2 was complaining about duplicate rows, which should not be the case. After a bit of investigation, it turned out that the problem was of course, not the inputs but duplicate file selection.  Here is the history with the error reproduced multiple times: https://usegalaxy.eu/u/videmp/h/deseq2-duplicate-genes-error-investigation

**To Reproduce**
1. Take a successful run
2. Unselect all the count files for one of the factor levels
3. While selecting again, double click on of the count files
4. Run the tool.
5. If it is error state, check one of the output dataset details to see the duplicated count file which was double clicked.

### PR DESCRIPTION
**Pull request by davelopez**
Fixes #19803

## Before

https://github.com/user-attachments/assets/659436bb-6f0e-4877-82e3-c1050b92c5c9

## After

https://github.com/user-attachments/assets/beee90a8-ac68-43d9-ad59-719dc044a4a0

## How to test the changes?
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/Form/Elements/FormData/FormData.vue [hunk 1]
```diff
@@ -427,7 +428,10 @@ function handleIncoming(incoming: Record<string, unknown> | Record<string, unkno
                     if (config.multiple) {
                         const newValues = currentValue.value ? currentValue.value.slice() : [];
                         incomingValues.forEach((v) => {
-                            newValues.push(v);
+                            // Avoid duplicates
```
Comment (mvdbeek) [inline client/src/components/Form/Elements/FormData/FormData.vue]: It seems like we'd ideally want to prevent the drop the same way we prevent dropping an invalid datatype?

**Review by mvdbeek — APPROVED** [review]

File: client/src/components/Form/Elements/FormData/FormData.vue (hunk 1 above)
Comment (davelopez) [reply client/src/components/Form/Elements/FormData/FormData.vue]: Ahh good point! I'll check how it is done and update this.

Comment (davelopez) [reply client/src/components/Form/Elements/FormData/FormData.vue]: I've updated the screencast, now it highlights the warning when the entry is duplicated.

image

**Comment by mvdbeek** [comment]
Awesome, thanks for going the extra mile @davelopez!
