### PR TITLE
[21.09] Fix dataset details and drag and drop

### LINKED ISSUE #12911: Forcing input into tool from history from a collection chooses wrong hidden file unless file is expanded
**Forcing input into tool from history from a collection chooses wrong hidden file unless file is expanded**

https://user-images.githubusercontent.com/20641402/141484788-66def1ac-f17b-431e-ad74-2261ce463eb5.mp4

When choosing a dataset from a collection and forcing it as input to a tool, the wrong input dataset is chosen.

Upon expanding the dataset first, and trying again, then the correct input dataset is chosen.

**Galaxy Version and/or server at which you observed the bug**

Galaxy Version:  usegalaxy.eu/api/version:   

    {"version_major": "21.05", "version_minor": "1.dev0"}

**To Reproduce**
1. Click on a tool
2. Expand a collection in your history
3. Drag the desired dataset into the input data field of the tool
4. Observe the wrong hidden input is loaded
5. Expand the desired dataset by click on its name
3. Drag the desired dataset into the input data field of the tool
4. Observe that the right hidden input is loaded

**Expected behavior*

That the right hidden input is loaded without having to expand the name first

### PR DESCRIPTION
**Pull request by mvdbeek**
Fixes #12911 and an issue that @Delphine-L reported where the "View details" button on currently running datasets in a collection point to the wrong dataset id. 

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:

Run a collection job that sleeps for a while and make sure the view details page makes sense.
Haven't included tests here since this is very specific to the backbone view and we're not going to do this magic in vue.

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @mvdbeek

File: client/src/mvc/dataset/dataset-li.js [hunk 1]
```diff
@@ -279,8 +279,9 @@ export var DatasetListItemView = _super.extend(
                 target: this.linkTarget,
                 faIcon: "fa-info-circle",
                 onclick: (ev) => {
+                    console.log("model", this.model);
```
Comment (dannon) [inline client/src/mvc/dataset/dataset-li.js]:
```suggestion
```

**Review by dannon — APPROVED** [review]
