### PR TITLE
[24.1] Fix dataset details polling re-render

### LINKED ISSUE #18375: Polling in ``datasets/{dataset_id}/details`` re-renders entire page
If you run a job and open the job info / dataset info page the whole component re-renders:

rendering

### PR DESCRIPTION
**Pull request by itisAliRH**
Closes #18375

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/DatasetInformation/DatasetDetails.vue [hunk 1]
```diff
@@ -124,7 +124,9 @@ onUnmounted(() => {
 
                 <JobDestinationParams v-if="currentUser?.is_admin" :job-id="dataset.creating_job" />
 
-                <JobDependencies v-if="jobDetails.dependencies" :dependencies="jobDetails.dependencies" />
+                <JobDependencies
+                    v-if="!jobLoading && jobDetails.dependencies"
```
Comment (mvdbeek) [inline client/src/components/DatasetInformation/DatasetDetails.vue]: Could you instead change `jobLoading` to `hasJobDetails` or something like that, meaning this variable can't revert from true to false ?

File: client/src/components/DatasetInformation/DatasetDetails.vue [hunk 2]
```diff
@@ -124,7 +124,7 @@ onUnmounted(() => {
 
                 <JobDestinationParams v-if="currentUser?.is_admin" :job-id="dataset.creating_job" />
 
-                <JobDependencies v-if="jobDetails.dependencies" :dependencies="jobDetails.dependencies" />
+                <JobDependencies v-if="jobDetails?.dependencies" :dependencies="jobDetails.dependencies" />
```
Comment (mvdbeek) [inline client/src/components/DatasetInformation/DatasetDetails.vue:122]: Now you're not using `jobLoading` at all so you can remove that variable

**Review by dannon — APPROVED** [review]

**Comment by mvdbeek** [comment]
Thanks a lot @itisAliRH!
