### PR TITLE
[24.2] Fix cancellation of workflow scheduling

### LINKED ISSUE #19237: [24.2] Cannot cancel workflow when it is running
https://github.com/user-attachments/assets/720136b8-1d1e-4e82-8e9a-8b8e4ad898c6

Galaxy Version: dev (24.2)

### PR DESCRIPTION
**Pull request by ahmedhamidawan**
Fixes https://github.com/galaxyproject/galaxy/issues/19237

Also:
- Fixes `force` router push in `WorkflowRunButton`
- Consolidates styling of `WorkflowNavigationTitle` with the tool form header styling

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/WorkflowInvocationState/WorkflowInvocationState.vue [hunk 1]
```diff
@@ -219,11 +220,22 @@ async function pollJobStatesUntilTerminal() {
...
+    try {
+        cancellingInvocation.value = true;
+        await cancelWorkflowScheduling(props.invocationId);
+    } catch (e) {
+        onError(e);
+    } finally {
+        emit("invocation-cancelled");
+
+        // Update the invocation state to reflect the cancellation
+        setTimeout(async () => {
```
Comment (mvdbeek) [inline client/src/components/WorkflowInvocationState/WorkflowInvocationState.vue]: Why the arbitrary timeout here ? I think the responsibility of this method is to to make the request and disable the cancel button. When all of this arrives at the scheduler depends on how busy the workflow scheduler is.

Comment (ahmedhamidawan) [reply client/src/components/WorkflowInvocationState/WorkflowInvocationState.vue]: I just added the fetches (along with a timeout) because without them, this can happen:

https://github.com/user-attachments/assets/70520d79-45c3-471f-98cd-249a65f19992

I.e.: The invocation state is never updated in the store since we stop fetching.

Comment (mvdbeek) [reply client/src/components/WorkflowInvocationState/WorkflowInvocationState.vue]: Well the state of those jobs is still going to change though, no fixed amount of time changes that. You can stop polling the invocation, but not the jobs.

Comment (ahmedhamidawan) [reply client/src/components/WorkflowInvocationState/WorkflowInvocationState.vue]: You're right, and the jobs do poll after this, until `jobStatesTerminal === true`
But the invocation object locally here doesn't update; I'm looking for a way to move the `cancelWorkflowSceduling` function to the invocation store to update invocation there when it is cancelling.

Comment (ahmedhamidawan) [reply client/src/components/WorkflowInvocationState/WorkflowInvocationState.vue]: This next commit 69ae867ae604ee2ed6b5ec6b49c1665cb04377cd fixes this, the fetch is required to update the graph when the state becomes `cancelling`.

Comment (mvdbeek) [reply client/src/components/WorkflowInvocationState/WorkflowInvocationState.vue]: Looks good, thank you!
