### PR TITLE
[24.1] Fix invocation view steps scroll bug

### LINKED ISSUE #18443: Fix invocation view steps list scroll bug
When you click on a step in the invocation graph, you are supposed to scroll the step in the step list into view, however, it can often scroll to the bottom of the list if the number of steps is very high.

### PR DESCRIPTION
**Pull request by ahmedhamidawan**
Fixes https://github.com/galaxyproject/galaxy/issues/18443

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/Workflow/Editor/WorkflowGraph.vue [hunk 1]
```diff
@@ -103,6 +105,7 @@ const props = defineProps({
     isInvocation: { type: Boolean, default: false },
     showMinimap: { type: Boolean, default: true },
     showZoomControls: { type: Boolean, default: true },
+    lowerZIndices: { type: Boolean, default: false },
```
Comment (mvdbeek) [inline client/src/components/Workflow/Editor/WorkflowGraph.vue]: Not too familiar with this, is this the recommended way to set the z-index ? Naively I'd think you would override a css rule in InvocationGraph.vue ?

Comment (ahmedhamidawan) [reply client/src/components/Workflow/Editor/WorkflowGraph.vue]: Actually overriding a css rule is a better idea, I'll do that

Comment (ahmedhamidawan) [reply client/src/components/Workflow/Editor/WorkflowGraph.vue]: Done, overriding css alone did it, thank you!
