### PR TITLE
[24.1] Fix display tags in FormSelect when available

### LINKED ISSUE #18667: Dataset chooser does not show tags anymore
**Describe the bug**

This worked until recently (except for choosing multiple datasets). But this might be intended, becuase datasets might have many tags which would be nasty fur UI. 

Just want to make sure.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1

### PR DESCRIPTION
**Pull request by davelopez**
Fixes #18667

FixFormSelectorTags

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:
  1. Follow the instructions in #18667

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by davelopez** [comment]
Currently, the filtering will not take into account the tags, only the main "label". Did the previous component filter by tag too in the search box?

**Comment by ElectronicBlueberry** [comment]
did you do a quick performance test for very large histories?

**Comment by davelopez** [comment]
Nope, if this was available before I just hope it shouldn't be worse than before. :sweat_smile: 

This is loading everything and is not (nor was) using any kind of pagination before I'm afraid.

**Comment by ElectronicBlueberry** [comment]
I'm worried mostly about the search, and how responsive it feels while typing. I think we have a filter worker which could be used here in case it's unresponsive.

**Comment by davelopez** [comment]
>  I think we have a filter worker which could be used here in case it's unresponsive.

Ahh cool! I'm happy to use it then. I'll search for it.

File: client/src/components/Form/Elements/FormSelect.vue [hunk 1]
```diff
@@ -51,19 +55,22 @@ const emit = defineEmits<{
     (e: "input", value: SelectValue | Array<SelectValue>): void;
 }>();
 
+const filter = ref("");
+const filteredOptions = useFilterObjectArray(props.options, filter, ["label", "value"]);
```
Comment (davelopez) [inline client/src/components/Form/Elements/FormSelect.vue]: @ElectronicBlueberry is this what you had in mind?

Unfortunately, I cannot filter by tags because the filter expects only the keys of the object and in this case, the tags are in the sub-object "value.tags" :thinking:

Comment (davelopez) [reply client/src/components/Form/Elements/FormSelect.vue]: I decided to allow referencing nested fields when filtering with a "naive" approach of providing a list of strings as "path" to the nested field in https://github.com/galaxyproject/galaxy/pull/18918/commits/5bccb6f28d2dc7c8133afa8c346dcd7ed9cd356f

It works on my testing although I had to add a mock implementation because obviously, the existing jest tests didn't like the worker :sweat_smile:

Comment (davelopez) [reply client/src/components/Form/Elements/FormSelect.vue]: Hmmm nope, now there are some issues when switching histories... when you try to filter after switching histories it doesn't show the correct items... I must have missed something... :thinking: I'm probably using the worker in a suboptimal way since I can see some warnings in the console too:

```
[Vue warn]: onScopeDispose() is called when there is no active effect scope to be associated with.
```

Any ideas?

Comment (ElectronicBlueberry) [reply client/src/components/Form/Elements/FormSelect.vue]: The options are not updating because passing props.options to the composable is not reactive. This is because the acessor on props is called in the components setup function during the function call, and not within the composable, so the reactive dependency cannot be established. Wrap props.options in a computed or getter function to fix this. This can be done inline.

Comment (davelopez) [reply client/src/components/Form/Elements/FormSelect.vue]: Do you mean something like https://github.com/galaxyproject/galaxy/pull/18918/commits/72bb11c10c359385707535fdec47e8fcfbc75b26?

I'm afraid it doesn't work or I'm not getting it right... :thinking:

Comment (davelopez) [reply client/src/components/Form/Elements/FormSelect.vue]: Thank you @ElectronicBlueberry I think I got it working now! :+1:

**Comment by davelopez** [comment]
It should be ready to review :)

**Comment by davelopez** [comment]
@ElectronicBlueberry, there is something about reusing the worker that breaks some selenium tests. I've tried for a long time to figure out what it is, but I can't see any problem with it :thinking: 

Do you think this is acceptable without reusing the worker as a fix? We can try to optimize it in the dev branch if this is a performance concern. What do you think?

**Comment by davelopez** [comment]
So all the tests magically passed for this one? :thinking: 

I'll rebase...

**Review by ElectronicBlueberry — APPROVED** [review]
