### PR TITLE
[26.0] Fix infinite request loop on dataset preview fetch failure

### LINKED ISSUE #21863: Navigating to a dataset preview creates request loop in some edge cases
If you don't have access to the dataset or the ID is wrong (or whatever makes the dataset fetch fail), then a request will be attempted indefinitely.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 25.1

**Browser and Operating System**
Operating System: Windows, Linux, macOS
Browser: Firefox, Chrome, Chrome-based, Safari

**To Reproduce**
1. Go to https://<galaxy_instance>/datasets/b887d74393f85b6d/preview
2. Make sure you are not the owner of dataset b887d74393f85b6d
3. Check the browser's network tab

**Expected behavior**
After a failed request or limited retries, the requests should stop and display an appropriate error message.

### PR DESCRIPTION
**Pull request by dannon**
When navigating to a dataset preview for a dataset you can't access (or with a bad ID), the `useKeyedCache` composable would retry the failed fetch indefinitely. On error, nothing was written to `storedItems`, so the next reactive evaluation of `getItemById` would see `undefined` and fire off another request. This adds a check against `loadingErrors` to stop that loop, and updates `DatasetView` to show an error message instead of spinning forever.

Fixes #21863

### CODE REVIEW

File: client/src/composables/keyedCache.ts [hunk 1]
```diff
@@ -53,7 +53,9 @@ export function useKeyedCache<T>(
     const getItemById = computed(() => {
         return (id: string) => {
             const item = storedItems.value[id];
-            if (shouldFetch(item)) {
+            // TODO: consider allowing retries for transient errors (e.g. 5xx, network)
```
Comment (mvdbeek) [inline client/src/composables/keyedCache.ts]: Should probably also keep going on 429 ... could you give that a shot ? We do have rate limiting on on usegalaxy.org

**Review by mvdbeek — APPROVED** [review]

**Comment by dannon** [comment]
One note, there are a bunch of other stores also using `useKeyedCache` with a plain rethrowSimple that may need review?  Not sure we want to do that against 26.0 at this point, but worth considering moving forward that these should use consistent retry handling.
