### PR TITLE
Frontend tool search bug fix

### LINKED ISSUE #14438: Bug on Tool Search
**Describe the bug**
Moderate front-end bug(s) on the Tool Search. Possibly more than one bug. Possible data bug too.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**

**Screenshots**
### Issue 1: Want same number of tools on Tool Panel (frontend) and API (backend)
Greenshot 2022-08-11 16 00 13

### Issue 2: Want same position on Tool Panel (frontend) and API (backend)
Greenshot 2022-08-11 15 47 31
Greenshot 2022-08-11 15 26 49

### Issue 3: Want only one version of the Tool
Greenshot 2022-08-11 15 23 16
Greenshot 2022-08-11 15 21 21
Greenshot 2022-08-11 15 21 29

**Additional context**

@tcollins2011

### PR DESCRIPTION
**Pull request by hujambo-dunia**
Fixes #14438

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. Test script included. However, if testing locally, will need to test on an environment with realistic data (for example, from usegalaxy.org or usegalaxy.eu).
  2. Then, will need to hook the realistic (static) data into the Tool Store api which produces the `tools` variable (in this `utilities.js`).
  3. From there, you can _optionally_ hook the Results api from Whoosh which produces the `results` variable (in this `utilities.js`).
  4. Referencing the included test script should provide clarity on these manual steps above.

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

File: client/src/components/Panels/utilities.js [hunk 1]
```diff
@@ -1,86 +1,136 @@
-export function filterToolSections(layout, results) {
-    if (results) {
-        results = normalize_results(results);
-        const filteredLayout = layout.map((section) => {
-            var toolRes = [];
-            if (section.elems) {
-                section.elems.forEach((el) => {
-                    if (
-                        (!el.text && results.includes(el.id)) ||
-                        (el.tool_shed_repository && results.includes(el.tool_shed_repository.name))
```
Comment (dannon) [inline client/src/components/Panels/utilities.js:10]: Just a note to double-check (with a test, ideally) the logic showing favorites independent of version; xref https://github.com/galaxyproject/galaxy/pull/9873

Comment (hujambo-dunia) [reply client/src/components/Panels/utilities.js:10]: @dannon Confirmed. The tools filter methods will still work with the Favorites independent of version. The front-end unit test attached to this PR includes coverage for matching the Tools store to the Favorites results (as of course it includes coverage for matching the Tools store to the Whoosh Search results).

File: client/src/components/Panels/utilities.js [hunk 2]
```diff
@@ -1,33 +1,96 @@
...
-                        toolRes.push(el);
-                    }
-                });
-            }
-            // sort tools in section by rank in results
-            toolRes.sort((tool1, tool2) => {
-                return results.indexOf(tool1.id) - results.indexOf(tool2.id);
+import { orderBy } from "lodash";
+
+export class toolSearch {
```
Comment (guerler) [inline client/src/components/Panels/utilities.js]: As mentioned, I suggest to not use a class instance here but just utility functions with defaults. These functions can be stateless.

**Review by guerler — APPROVED** [review]
