### PR TITLE
 Fix active tab highlighting

### LINKED ISSUE #4846: missing menu highlight for workflow tab
screenshot 2017-10-23 14 45 28

### PR DESCRIPTION
**Pull request by qiagu**
fixes #4846 and others

### CODE REVIEW

**Comment by dannon** [comment]
@qiagu Thanks for tracking down more of these.  I'm seeing one issue with the highlighting dropping off.  To reproduce, try this example:

Click Shared Data -> Histories.  Note that Shared Data is highlighted correctly.
Now click the "Help" dropdown without selecting anything (like a user might, when just checking to see what options in menus are).  Note that the active tab has been unset.

The same issue doesn't happen when "Analyze Data" is the active tab.

**Comment by qiagu** [comment]
Good catch! It's strange that the highlighting of workflow tab doesn't drop off. I'll try to tack down the issue.

**Comment by dannon** [comment]
@qiagu Great!  Let me know if I can help.

**Comment by qiagu** [comment]
Thanks. I guess the issue has been fixed, although I don't completely understand the code. Please check back.

File: client/galaxy/scripts/apps/analysis.js [hunk 1]
```diff
@@ -94,15 +94,20 @@ window.app = function app(options, bootstrapped) {
             var model = new UserPreferences.Model({
                 user_id: Galaxy.params.id
             });
-            this.page.display(new FormWrapper.View(model.get(form_id)));
+            this.page.display(new FormWrapper.View(_.extend(
+                model.get(form_id),
+                {active_tab: "user"}
```
Comment (guerler) [inline client/galaxy/scripts/apps/analysis.js:99]: This should probably be a parameter of `page` instead of the underlying view:
`this.page.display(VIEW, {active_tab:  "user"})`.

**Comment by qiagu** [comment]
@guerler This patch is a followup of previous PR (https://github.com/galaxyproject/galaxy/pull/5593).  I like your idea though, which could make the problem simpler.

File: client/galaxy/scripts/apps/analysis.js (hunk 1 above)
Comment (dannon) [reply client/galaxy/scripts/apps/analysis.js:99]: @guerler Unfortunately it's not as clean in this particular instance due to the generic `FormWrapper` used, but the approach was chosen to allow better separation of concerns -- that is, allowing most concrete views to document/mark their own titles/tabs as appropriate.  I'll agree it's a little complicated in situations like the generic display above, requiring this extra context in the controller action, but as we build out more concrete views these should continue to go away.

We can revisit it later, (after an upcoming rewrite of the masthead, preferably -- something I've been poking at), but I think delegating to the toplevel view attributes as has been done here (and in previous PRs) is the best path forward now.

Comment (guerler) [reply client/galaxy/scripts/apps/analysis.js:99]: Alright, sounds good.

**Comment by dannon** [comment]
Thanks again for following up on this @qiagu.

**Comment by qiagu** [comment]
@dannon It's my pleasure. Thank you for your comments and merging the code.
