### PR TITLE
[22.05] Fix showing invocations for a particular workflow.

### LINKED ISSUE #14101: [release-testing] Viewing invocations for an individual workflow shows all invocations
Testing https://github.com/galaxyproject/galaxy/pull/13792. Going to the workflow menu, choosing a workflow, clicking the dropdown menu and clicking `Invocations` should display only invocations for that particular workflow. Instead, all invocations are shown (`/workflows/9c49d5aac9fe9dcc/invocations` and `/workflows/invocations` have the same content).

### PR DESCRIPTION
**Pull request by jmchilton**
Fixes https://github.com/galaxyproject/galaxy/issues/14101.

I think https://github.com/galaxyproject/galaxy/pull/14067 would have caught this. 

## How to test the changes?
- [x] Instructions for manual testing are as follows:
  1. See referenced issue. 

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

File: client/src/components/Workflow/StoredWorkflowInvocations.vue [hunk 1]
```diff
@@ -1,6 +1,6 @@
 <template>
     <CurrentUser v-slot="{ user }">
-        <StoredWorkflowDetailsProvider v-slot="{ result: item, loading }" :stored-workflow-id="storedWorkflowId">
+        <StoredWorkflowDetailsProvider v-slot="{ result: item, loading }" :storedWorkflowId="storedWorkflowId">
```
Comment (guerler) [inline client/src/components/Workflow/StoredWorkflowInvocations.vue]: This might trigger lint warnings.

Comment (jmchilton) [reply client/src/components/Workflow/StoredWorkflowInvocations.vue]: I guess this is the use of ``this.$attrs`` in SingleQueryProvider. Should we do something to camel case those automatically?

The other uses are even worse than either of these options right (using camelCase in the template or auto-converting attributes)?

```
<JobProblemProvider v-slot="{ result: jobProblems }" :jobid="dataset.creating_job" @error="onError">
```

File: client/src/components/Workflow/Invocations.vue [hunk 2]
```diff
@@ -65,7 +65,10 @@
                 <UtcDate :date="data.value" mode="elapsed" />
             </template>
             <template v-slot:cell(execute)="data">
-                <WorkflowRunButton :id="getWorkflowByInstanceId(data.item.workflow_id).id" :root="root" />
+                <WorkflowRunButton
+                    v-if="getWorkflowByInstanceId(data.item.workflow_id)"
```
Comment (mvdbeek) [inline client/src/components/Workflow/Invocations.vue]: This isn't the only issue here, should I pull out https://github.com/galaxyproject/galaxy/pull/14067/commits/8be0f90714fa2edcb893ada7b0604ed681e6de07 ?

File: client/src/components/Workflow/StoredWorkflowInvocations.vue (hunk 1 above)
Comment (mvdbeek) [reply client/src/components/Workflow/StoredWorkflowInvocations.vue]: Is this change part of the fix ? https://v2.vuejs.org/v2/style-guide/?redirect=true#Prop-name-casing-strongly-recommended seems to suggest that `:stored-workflow-id` is equivalent to `:storedWorkflowId`, but that `:stored-workflow-id` is recommended.

Comment (jmchilton) [reply client/src/components/Workflow/StoredWorkflowInvocations.vue]: It would be equivalent but we're using ``$attrs`` directly as a function arguments, we're not using them as reactive properties. This is the main issue IMO - the other part of this with the ``v-if`` is essentially purely cosmetic to prevent console errors.

File: client/src/components/Workflow/Invocations.vue (hunk 2 above)
Comment (jmchilton) [reply client/src/components/Workflow/Invocations.vue]: That is a better fix than mine!

File: client/src/components/Workflow/StoredWorkflowInvocations.vue (hunk 1 above)
Comment (guerler) [reply client/src/components/Workflow/StoredWorkflowInvocations.vue]: I see, that makes sense. I thought they were already automatically camel cased, I might create a ticket to resolve it.

Comment (guerler) [reply client/src/components/Workflow/StoredWorkflowInvocations.vue]: For generic store providers the attributes are converted to camel case fyi, should maybe place this function somewhere and reuse it in the future, or discuss a better way to deal with this. https://github.com/galaxyproject/galaxy/blob/dev/client/src/components/providers/storeProviders.js#L187

File: client/src/components/DatasetInformation/DatasetError.vue [hunk 3]
```diff
@@ -8,7 +8,7 @@
             <JobDetailsProvider
                 v-if="!datasetLoading"
                 v-slot="{ result: jobDetails, loading }"
-                :jobid="dataset.creating_job"
+                :jobId="dataset.creating_job"
```
Comment (guerler) [inline client/src/components/DatasetInformation/DatasetError.vue:11]: Not critical, but now we can also write `job-id` instead, right? Thank you for adding the Mixins.
