### PR TITLE
[22.05] Fix display collection error in history items

### LINKED ISSUE #14980: Collection history outputs do not show job failed info
Related to https://github.com/galaxyproject/galaxy/issues/14128.

When a job fails and the only output is a collection, there seems to be no way to view the info on the failed run (i.e. the "info" and "bug report" icons are missing.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05 / dev.usegalaxy.org.au
Commit: 22.05 release

**To Reproduce**
Steps to reproduce the behaviour:
1. On dev.usegalaxy.org.au, run the ["Untar" tool](https://dev.usegalaxy.org.au/tool_runner?tool_id=tar_extract) on a tar archive
3. See the history output when the tool breaks
4. Repeat the above with any failing tool that outputs a collection only, on release 22.05

**Expected behaviour**
The collection should allow access to the tool run info, and bug report submission by displaying the appropriate icons. Perhaps the collection item should expand when clicked to show these icons, rather than dropping into the collection immediately. The UI could show an additional icon (like a chevron) to drop into the collection in one click.

**Screenshots**
The failed history output:
image

After clicking on the output:
image

### PR DESCRIPTION
**Pull request by davelopez**
Fixes (partially) #14980

I assume the "3 dot menu" was dropped for a reason so the first pass at fixing this is just "shoving" the missing buttons in the `ContentOptions` component. I can explore other options if there are better ideas on where to put them.

If the collection has a `job_source_id` and `job_source_type='Job'` then the show details button is displayed for the collection:
image

I'll follow up by adding an Error report button for collection on the `dev` branch since it's not directly supported for collections and will require some more changes/refactorings.

## How to test the changes?
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:
  1. Follow the steps on #14980 or use the `job_properties` testing tool with the failure property enabled.
  2. You can now access the job details and report an error.

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/History/Content/ContentItem.vue [hunk 1]
```diff
@@ -176,6 +178,8 @@ export default {
             if (this.isCollection) {
                 return {
                     edit: `collection/edit/${id}`,
+                    showDetails: this.item.job_source_id ? `jobs/${this.item.job_source_id}/view` : null,
+                    reportError: `datasets/error?dataset_id=${id}`, // TODO use proper url for collections
```
Comment (davelopez) [inline client/src/components/History/Content/ContentItem.vue]: Is it correct to use the same URL for reporting errors on collections? I couldn't find something like `collections/error`

Comment (mvdbeek) [reply client/src/components/History/Content/ContentItem.vue]: No, that'll be the wrong id ... but in any case this should operate on the job, i think

**Comment by mvdbeek** [comment]
That is a really cool fix, thanks @davelopez! Can you add or extend one of the selenium tests too ?

File: client/src/components/History/Content/ContentItem.vue (hunk 1 above)
Comment (davelopez) [reply client/src/components/History/Content/ContentItem.vue]: Oh right! I thought it was just using the `creating_job` of the content item even if everything was named as "dataset" but I see the DatasetProvider now... :sweat_smile: 
I guess I should refactor it to accept a job and create another wrapper component that uses the collections provider :thinking:

Comment (davelopez) [reply client/src/components/History/Content/ContentItem.vue]: By the way, should I drop the report error button for collections from this PR and add it on dev? If this is somewhat of a new feature?

Comment (mvdbeek) [reply client/src/components/History/Content/ContentItem.vue]: Either way is OK with me, I'll let you decide.

File: lib/galaxy_test/selenium/test_history_panel_collections.py [hunk 2]
```diff
@@ -132,6 +132,21 @@ def test_output_collection_states_running(self):
...
+        failed_hid = failed_collection["hid"]
+        self.home()
+
+        ok_collection_element = self.history_panel_wait_for_hid_state(ok_hid, "ok")
+        failed_collection_element = self.history_panel_wait_for_hid_state(failed_hid, "error")
+
+        ok_collection_element.collection_job_details_button.wait_for_and_click()
+        self.screenshot("history_panel_collections_job_details_ok")
+        failed_collection_element.collection_job_details_button.wait_for_and_click()
+        self.screenshot("history_panel_collections_job_details_failed")
```
Comment (davelopez) [inline lib/galaxy_test/selenium/test_history_panel_collections.py]: I'm quite confused with this test result...
I was expecting the failed collection to have more information about the error, but apparently, both collections share the same `job_source_id`... is this correct or is it a bug?

history_panel_collections_job_details_ok

history_panel_collections_job_details_failed

Comment (mvdbeek) [reply lib/galaxy_test/selenium/test_history_panel_collections.py]: That is not correct, is it possible that the page hasn't rendered yet ? It also still says `__DATA_FETCH__` in the screenshot.

Comment (davelopez) [reply lib/galaxy_test/selenium/test_history_panel_collections.py]: The page has been rendered for sure, I have some wait time before taking each screenshot locally and I can see the reload of both when running the test visually. Both collections seem to have the same `job_source_id` if I inspect the payload.

Comment (mvdbeek) [inline lib/galaxy_test/selenium/test_history_panel_collections.py]: I think in both cases you'll want to wait and assert for something specific in the error page, like the tool id for instance ?

Comment (mvdbeek) [reply lib/galaxy_test/selenium/test_history_panel_collections.py]: But that's not true for the screenshot you're showing here.

Comment (mvdbeek) [reply lib/galaxy_test/selenium/test_history_panel_collections.py]: IOW there's no way for the rendering to have finished before taking the screenshots (that doesn't mean there couldn't be another issue on top of that of course), but also the screenshots aren't a test in itself, you really have to assert something.

Comment (davelopez) [reply lib/galaxy_test/selenium/test_history_panel_collections.py]: Yes, sorry I wasn't clear that these screenshots were taken while I was manually debugging, not just plain running the test as it is right now in the branch (of course those would not render properly). So I could make sure both pages were truly reloaded and also I could inspect the API response in the dev tools.

Comment (davelopez) [reply lib/galaxy_test/selenium/test_history_panel_collections.py]: This is the API response for the contents of the history:
```json
{
    "stats": {
        "total_matches": 2
    },
    "contents": [
        {
            "id": "529fd61ab1c6cc36",
            "name": "exit_code_from_file on collection 1",
            "history_id": "529fd61ab1c6cc36",
            "hid": 6,
            "history_content_type": "dataset_collection",
            "deleted": false,
            "visible": true,
            "type_id": "dataset_collection-529fd61ab1c6cc36",
            "type": "collection",
            "create_time": "2022-11-22T10:40:47.361203",
            "update_time": "2022-11-22T10:40:48.378440",
            "url": "/api/histories/529fd61ab1c6cc36/contents/dataset_collections/529fd61ab1c6cc36",
            "tags": [],
            "model_class": "HistoryDatasetCollectionAssociation",
            "collection_type": "list",
            "populated_state": "ok",
            "populated_state_message": null,
            "element_count": 4,
            "job_source_id": "adb5f5c93f827949",
            "job_source_type": "ImplicitCollectionJobs",
            "job_state_summary": {
                "all_jobs": 4,
                "new": 0,
                "waiting": 0,
                "running": 0,
                "error": 2,
                "paused": 0,
                "deleted_new": 0,
                "resubmitted": 0,
                "queued": 0,
                "ok": 2,
                "failed": 0,
                "deleted": 0,
                "upload": 0
            },
            "contents_url": "/api/dataset_collections/529fd61ab1c6cc36/contents/529fd61ab1c6cc36",
            "collection_id": "529fd61ab1c6cc36",
            "elements_datatypes": [
                "data"
            ]
        },
        {
            "id": "adb5f5c93f827949",
            "name": "Test Dataset Collection",
            "history_id": "529fd61ab1c6cc36",
            "hid": 1,
            "history_content_type": "dataset_collection",
            "deleted": false,
            "visible": true,
            "type_id": "dataset_collection-adb5f5c93f827949",
            "type": "collection",
            "create_time": "2022-11-22T10:40:07.265526",
            "update_time": "2022-11-22T10:40:43.248358",
            "url": "/api/histories/529fd61ab1c6cc36/contents/dataset_collections/adb5f5c93f827949",
            "tags": [],
            "model_class": "HistoryDatasetCollectionAssociation",
            "collection_type": "list",
            "populated_state": "ok",
            "populated_state_message": null,
            "element_count": 4,
            "job_source_id": "adb5f5c93f827949",
            "job_source_type": "Job",
            "job_state_summary": {
                "all_jobs": 1,
                "new": 0,
                "waiting": 0,
                "running": 0,
                "error": 0,
                "paused": 0,
                "deleted_new": 0,
                "resubmitted": 0,
                "queued": 0,
                "ok": 1,
                "failed": 0,
                "deleted": 0,
                "upload": 0
            },
            "contents_url": "/api/dataset_collections/adb5f5c93f827949/contents/adb5f5c93f827949",
            "collection_id": "adb5f5c93f827949",
            "elements_datatypes": [
                "txt"
            ]
        }
    ]
}
```
If you look closely both have the same `"job_source_id": "adb5f5c93f827949"` but now I see that they have different `job_source_type`.

Comment (mvdbeek) [reply lib/galaxy_test/selenium/test_history_panel_collections.py]: Yep, so one is basically `job: 1` and the other is `implicit_collection_job: 1`

File: client/src/components/History/Content/ContentItem.vue [hunk 3]
```diff
@@ -176,6 +177,7 @@ export default {
             if (this.isCollection) {
                 return {
                     edit: `collection/edit/${id}`,
+                    showDetails: this.item.job_source_id ? `jobs/${this.item.job_source_id}/view` : null,
```
Comment (mvdbeek) [inline client/src/components/History/Content/ContentItem.vue]: I think you need to dispatch here on whether you got a job or a implicit collection job ... and in fact we don't have a implicit collection job info page. You need to pick another tool for the selenium test, one that creates a collection not by mapping over a collection.

Comment (davelopez) [reply client/src/components/History/Content/ContentItem.vue]: Thank you so much for the help Marius! now It all makes sense! :)

File: lib/galaxy_test/selenium/test_history_panel_collections.py [hunk 4]
```diff
@@ -132,6 +132,26 @@ def test_output_collection_states_running(self):
...
+        tool_exit_code_component = self.components.job_details.tool_exit_code.wait_for_visible()
+        self.screenshot("history_panel_collections_job_details_ok")
+        assert tool_id_component.text == "collection_creates_list"
+        assert int(tool_exit_code_component.text) == 0
+
+        failed_collection_element.collection_job_details_button.wait_for_and_click()
+        tool_id_component = self.components.job_details.galaxy_tool_id.wait_for_visible()
+        tool_exit_code_component = self.components.job_details.tool_exit_code.wait_for_visible()
+        self.screenshot("history_panel_collections_job_details_failed")
+        assert tool_id_component.text == "collection_creates_list_fail"
```
Comment (mvdbeek) [inline lib/galaxy_test/selenium/test_history_panel_collections.py]: I think the test would be more robust if you include the tool id in the selector, so that `wait_for_visible` would actually wait for the text to change. What could happen here is that depending how quickly the rerender occurs you still get the old tool id in tool_id_component.text and the test fails.

Comment (davelopez) [reply lib/galaxy_test/selenium/test_history_panel_collections.py]: Thanks for the hint! I definitely need to catch up with Selenium testing :sweat_smile: 
I will try that

Comment (davelopez) [reply lib/galaxy_test/selenium/test_history_panel_collections.py]: Ok, I think I got it now. It took me a while to figure out that the tool id text was actually surrounded by a lot of spaces :sweat_smile:

File: client/src/utils/navigation/navigation.yml [hunk 5]
```diff
@@ -944,3 +945,11 @@ charts:
   selectors:
     visualize_button: '.ui-portlet .button i.fa-line-chart'  # without icon - it waits on other buttons that aren't visible, need more specific class
     viewport_canvas: 'svg.charts-viewport-canvas'
+
+job_details:
+  selectors:
+    galaxy_tool_with_id:
+      type: xpath
+      selector: '//td[@id="galaxy-tool-id"][normalize-space(text()) = "${tool_id}"]'
```
Comment (mvdbeek) [inline client/src/utils/navigation/navigation.yml:953]: 💯

**Review by mvdbeek — APPROVED** [review]

File: lib/galaxy_test/selenium/test_history_panel_collections.py (hunk 4 above)
Comment (mvdbeek) [reply lib/galaxy_test/selenium/test_history_panel_collections.py]: Thanks for taking that extra step, really appreciate it!

**Comment by mvdbeek** [comment]
Thank you @davelopez!
