### PR TITLE
Fix unselect file in FTP uploader popup

### LINKED ISSUE #13645: Cannot unselect, selected FTP files in the uploader popup
**Describe the bug**
When clicking on the uploader FTP popup, a list appears, files selected once cannot be unselected.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Go to 'Upload Data'
2. Click on 'Choose FTP files' (requires FTP to be configured)
3. Select a file from the table in the popup
4. Notice how unselecting the entry is not possible

**Expected behavior**
Should unselect the file if clicked on.

### PR DESCRIPTION
**Pull request by itisAliRH**
Fixes #13645 

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

File: client/src/components/Upload/UploadBoxMixin.js [hunk 1]
```diff
@@ -242,7 +242,8 @@ export default {
             } else {
                 this.counterAnnounce--;
             }
-            this.uploadbox.remove(model.id);
+            const fileSetKey = model.get("file_path") + model.get("file_size");
+            this.uploadbox.remove(model.id, fileSetKey);
```
Comment (guerler) [inline client/src/components/Upload/UploadBoxMixin.js]: Do you we know why the `model.id` is not enough?

Comment (itisAliRH) [reply client/src/components/Upload/UploadBoxMixin.js]: [Here](https://github.com/galaxyproject/galaxy/pull/13652/files#diff-4943c3ffd7d0bc116b15b38b6e13ec2ebf9ec700284701e2a89733df17a3f04fR240) we check that selected file not existed in fileSet. Thus, if you select a file, then unselect it, it can't be selected anymore.

Comment (itisAliRH) [reply client/src/components/Upload/UploadBoxMixin.js]: see `client/src/utils/uploadbox.js:240`

Comment (guerler) [reply client/src/components/Upload/UploadBoxMixin.js]: I see now, I think we need to make sure that `model.id` is returned properly when `uploadbox.add` is called and then pass the `id` back to `uploadbox.remove()` as you already do. Removing the fileSetKey should happen within the `uploadbox` module. Otherwise other location which also call `uplodbox.remove()` will each have to manually generate and parse the fileSetKey.

File: client/src/utils/uploadbox.js [hunk 2]
```diff
@@ -245,13 +245,15 @@ export class UploadQueue {
                 }
             });
         }
+        // Returns last added file index.
+        return this.nextIndex - 1;
```
Comment (guerler) [inline client/src/utils/uploadbox.js:249]: We should not reduce this, the `id` is currently always a unique arbitrary number. Reducing this index might lead to duplicate model ids.

File: client/src/utils/uploadbox.js [hunk 3]
```diff
@@ -245,13 +245,15 @@ export class UploadQueue {
...
     }
 
     // Remove file from queue
-    remove(index) {
+    remove(index, fileSetKey) {
         // Removes the item identified by index.
```
Comment (guerler) [inline client/src/utils/uploadbox.js]: As mentioned above, we should use the `index` to grab the file from the queue here, and then, as you correctly do,  remove it from the fileSet.

File: client/src/utils/uploadbox.js [hunk 4]
```diff
@@ -245,13 +245,16 @@ export class UploadQueue {
...
 
-    // Remove file from queue
+    // Remove file from queue and file set by index
     remove(index) {
-        // Removes the item identified by index.
+        const file = this.queue.get(index);
+        const fileSetKey = file.name + file.size;
         // Returns true if an item was removed, and false otherwise.
-        return this.queue.delete(index);
+        return this.queue.delete(index) && this.fileSet.delete(fileSetKey);
```
Comment (guerler) [inline client/src/utils/uploadbox.js]: Is the return value used anywhere? If not I recommend to just execute both commands.

**Review by guerler — APPROVED** [review]
Thank you! This fixes the issue for me.

File: client/src/utils/uploadbox.js (hunk 4 above)
Comment (itisAliRH) [reply client/src/utils/uploadbox.js]: It's not. I removed it.
