### PR TITLE
[21.09] Fix output state handling, disable connectivity for conditionals

### LINKED ISSUE #12032: Workflow Editor - Connectors and/or noodle maintain incorrect state
This is related to https://github.com/galaxyproject/galaxy/pull/11683 and #10788

When using the workflow editor and connecting and disconnecting tools that have restrictions on their inputs/outputs the connector and/or noodles can lose the correct state.  I have attached a screen cap that exhibits the problem, but I am not sure if it specific to these tools.

**Tools**

1. Input Dataset Collection
1. [FeatureFinderMultiplex](toolshed.g2.bx.psu.edu/repos/galaxyp/openms_featurefindermultiplex/FeatureFinderMultiplex/2.6+galaxy0)
1. [IDMapper](toolshed.g2.bx.psu.edu/repos/galaxyp/openms_featurefindermultiplex/FeatureFinderMultiplex/2.6+galaxy0)

**Steps to Reproduce**

1. Create a new workflow
1. Add the above tools
1. In the `FeatureFinderMultiplex` configuration (right panel)
   1. Under `Optional outputs` Click `Select/Unselect all`
   1. Deselect output options so `out (Output file containting the individual peptide features)` is the only selected output.
1. Connect 2 -> 3
   - Note we get a single file noodle
1. Try to connect 1 -> 2
   - Note the warning about mismatched output and input formats. (expected behavior).
1. Delete noodle between 2 -> 3
1. Connect 1 -> 2 (note batch mode connection)
1. Connect 2 -> 3 (note batch mode connection)
   - So far so good.
1. Delete noodle between 1 -> 2
1. In the `FeatureFinderMultiplex` configuration (right panel)
   - Deselect the `out` option.
      - The noodle connecting 2  -> 3 is removed (expected behavior)
   1. Under `Optional outputs` Click `Select/Unselect all`
   1. Deselect output options so `out` is the only selected output again.
1. Reconnect noodle between 2 -> 3
   - Note we get a batch mode connection (unexpected behavior)
1. Delete the noodle between 2 -> 3 and reconnect.
   - Note we now get a single file connection (unexpected behavior)
1. Connect 1 -> 2
   - We no longer get a warning about the mismatched input/output types (unexpected behavior)

noodle-state

### LINKED ISSUE #12588: WF editor: "Add connection to module" not working for conditionals
**Describe the bug**

Not sure whether this is intentional or not, but In 21.09 the workflow editor offers "Add connection to module" (<->) also for outer conditional params.
Clicking on <-> for such a param, however, does not seem to have any effect except making the param unconfigurable.
No new workflow step input is appearing.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09

**To Reproduce**
Example tools where this can be seen are:
- https://usegalaxy.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/compose_text_param/compose_text_param/0.1.1

  <-> Choose the type of parameter for this field

- https://usegalaxy.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/devteam/bowtie2/bowtie2/2.4.2+galaxy0

  <-> Is this single or paired library

**Additional context**
Discovered during 21.09 release testing

### PR DESCRIPTION
**Pull request by guerler**
Fixes #12588. Also fixes an issue regarding the selection of active workflow outputs. In some cases clicking on the checkbox did not marked the checkbox properly. This happened particularly when directly clicking on the checkbox without selecting the node first.

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]
Thanks a lot!

File: client/src/components/Workflow/Editor/Forms/FormTool.vue [hunk 1]
```diff
@@ -124,6 +121,12 @@ export default {
                     }
                 }
             });
+            Utils.deepeach(inputs, (input) => {
+                if (input.type === "conditional") {
+                    input.connectable = false;
+                    input.test_param.collapsible_value = undefined;
+                }
+            });
```
Comment (mvdbeek) [inline client/src/components/Workflow/Editor/Forms/FormTool.vue:129]: I confirm this works, but can you explain why this needs to go into a second deepeach ? At first I thought it's important to set `input.collapsible_value` and `input.is_workflow` for conditional inputs as well, but that's not it, otherwise this would work as well (and save the second deepeach):
```diff
diff --git a/client/src/components/Workflow/Editor/Forms/FormTool.vue b/client/src/components/Workflow/Editor/Forms/FormTool.vue
index ee4f46182a..3873d44c5e 100644
--- a/client/src/components/Workflow/Editor/Forms/FormTool.vue
+++ b/client/src/components/Workflow/Editor/Forms/FormTool.vue
@@ -119,12 +119,10 @@ export default {
                             (input.options && input.options.length === 0) ||
                             ["integer", "float"].indexOf(input.type) != -1;
                     }
-                }
-            });
-            Utils.deepeach(inputs, (input) => {
-                if (input.type === "conditional") {
-                    input.connectable = false;
-                    input.test_param.collapsible_value = undefined;
+                    if (input.type === "conditional") {
+                        input.connectable = false;
+                        input.test_param.collapsible_value = undefined;
+                    }
                 }
             });
             return inputs;
```
I've been staring at this for some time, even printing out the params and diffing them, and I don't understand why this is not equivalent. Is this a disguised case of manipulating props (node in this case) ?

Comment (guerler) [reply client/src/components/Workflow/Editor/Forms/FormTool.vue:129]: Deepeach recursively traverses each of the nested objects in inputs. At first it reaches the conditional `input` which we use to configure the child-object `input.test_param`. This child-object will be visited by the recursion in a consecutive iteration. When it visits the input object of the `test_param` it treats it as a regular input parameter. This is why the two loops are separate. Alternatively, we could set a flag within the `test_param` object to tag it as conditional test parameter, then we could handle it in the same loop.

Comment (mvdbeek) [reply client/src/components/Workflow/Editor/Forms/FormTool.vue:129]: > it treats it as a regular input parameter.

... and resets connectable to true. Alright that makes sense. I don't know about adding another flag, probably premature optimization.

Is it possible that in a future iteration the form parameters themselves maintain the state in a way that it is directly consumable by the workflow form, so we can get rid of this ?

Comment (guerler) [reply client/src/components/Workflow/Editor/Forms/FormTool.vue:129]: We could just set something like `input.test_param._fixed = true` on the first visit and then recognize this flag when the `test_param` is visited by itself.

Comment (mvdbeek) [reply client/src/components/Workflow/Editor/Forms/FormTool.vue:129]: Performance-wise that is ok and what you suggested before, but I'd call it premature optimization until we know this is an issue. At most it's going to be twice as slow, that's not a big deal. My concern is more with manipulating the config form outside of the parameters and adding state to it.

IOW I have the intuition that the state should be kept with the parameters. We're special casing a few parameter types here, right ? And all this does is inform how the parameters are going to render. So if you make the Parameters accept a prop that defines whether we're in a workflow or regular tool form scenario the parameters themselves can decide if they have to display workflow specific elements. I hope that makes sense.
