### PR TITLE
[19.01] Fix routing when serving Galaxy at a prefix

### LINKED ISSUE #7162: Issues with prefix path (/galaxy)
I am using galaxy 18.09 version with old galaxy.ini format. 

I am getting javascript error in the multiple history view. When I debug the issue i realised that galaxy request url does not contains the prefix (/galaxy) . for example http://localhost:8082/api/histories/0a248a1f62a0cc04/contents/datasets/e90facaf332c3038 . This issue happens only in the multiple history view.

image

Also, several links in the top menu seems to be broken. In this case the prefix path is duplicated
http://localhost:8082/galaxy/galaxy/workflows/list?__identifer=h0cm1bzxuc
http://localhost:8082/galaxy/galaxy/visualizations?__identifer=lt0el2s7baq
http://localhost:8082/galaxy/galaxy/user?__identifer=39ze7z0ldbc
http://localhost:8082/galaxy/galaxy/custom_builds?__identifer=juay9tburl8

if would be great if someone can provide a solution to fix this issue.

### PR DESCRIPTION
**Pull request by dannon**
More galaxy-at-prefix issues fixed w/ backbone router.  Fixes #7162 (and more)
Fixed a CORS issue when welcome was external.
Prettier URLs by dropping the `__identifier` cruft after navigation.  Still annoying, but this makes nicer URLs until we have the vue router infra in.

### CODE REVIEW

**Comment by dannon** [comment]
I think the CircleCI build failure here is unrelated.  It occurs on all pre-dev PRs, right?

**Comment by martenson** [comment]
@dannon correct, circleci atm tests head of fork's branch so older branches won't have the config

**Comment by dannon** [comment]
@martenson Ok, cool, thanks for confirming that.

**Review by jmchilton — APPROVED** [review]

File: client/galaxy/scripts/layout/router.js [hunk 1]
```diff
@@ -12,17 +13,27 @@ var Router = Backbone.Router.extend({
         this.options = options;
     },
 
+    executeUseRouter: function(url) {
```
Comment (martenson) [inline client/galaxy/scripts/layout/router.js:16]: I am not sure about the naming here, what is a 'use router'?

Comment (dannon) [reply client/galaxy/scripts/layout/router.js:16]: It refers to the `__use_router__` navigation definition we use, this function executes the navigation intended by those targets.
