### PR TITLE
[20.09] Fix UTC Date date change

### LINKED ISSUE #10600: Workflow list sorting issue
Hi, 

just wanted to report a strange behaviour of the workflow list: 

On the EU Server the [workflow list](https://usegalaxy.eu/workflows/list) "updated" column seems not to move accordingly when sorting for other columns: 

Screenshot of original workflow list: 
wf_original_order

Clicking on "Name" sorts workflows according to name and it sorts all other columns accordingly, but the "updated" column stays exactly the same: 
wf_name_sorted

Thanks,
Melanie

### PR DESCRIPTION
**Pull request by OlegZharkov**
Took me a little while to get what is going on here. The Date stayed the same, even though sorting worked fine.

This PR will update date in `UtcDate.vue`  on props change. It will fix UtcDate sorting in Invocations, Datasetlist, InteractiveTools, LibraryFodler and WorkflowList tables. fixes https://github.com/galaxyproject/galaxy/issues/10600

Before:
Peek 2020-11-10 18-38

Now:
my-f-giff

thanks @foellmelanie for reporting

### CODE REVIEW

**Comment by dannon** [comment]
@OlegZharkov I started opening up a PR to your branch but this was faster.  I've just pushed a different approach to this branch here that I think is a bit simpler -- feel free to dump it if it isn't working for you or if you don't like it.

File: client/src/components/UtcDate.vue [hunk 1]
```diff
@@ -22,33 +22,22 @@ export default {
         },
         customFormat: {
             type: String,
+            default: null,
```
Comment (OlegZharkov) [inline client/src/components/UtcDate.vue:25]: why?

**Comment by OlegZharkov** [comment]
> @OlegZharkov I started opening up a PR to your branch but this was faster. I've just pushed a different approach to this branch here that I think is a bit simpler -- feel free to dump it if it isn't working for you or if you don't like it.

No worries, I tried this change and it works just fine. Thanks :+1:

File: client/src/components/UtcDate.vue (hunk 1 above)
Comment (dannon) [reply client/src/components/UtcDate.vue:25]: Props should always have explicit defaults.

**Review by bgruening — APPROVED** [review]
Thanks @OlegZharkov and @dannon!

**Comment by OlegZharkov** [comment]
thanks @bgruening @dannon
