### PR TITLE
[23.0] Fix dataset create time convert

### LINKED ISSUE #15301: The "Created" field in Dataset Information shows time as UTC, not local
**Describe the bug**
Within the dataset information fields, the "Created" date and time is being rendered as "UTC" time and not the local time. I cannot find a way to change or resolve this.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.01
Commit: d4001d18511fa9aba30da88fce5ee98f1b1a11bb

**To Reproduce**
1. Execute a tool in Galaxy
2. Select the link to the item in the History
3. Select the "View Details" button
4. Time will be displayed as "UTC" and not local time.

**Expected behavior**
The details about when the data set was created should be displayed in the lcoal time and not UTC.

**Screenshots**
Galaxy_Time_Issue

**Additional context**
Having the time stored in the database as UTC is perfectly acceptible, but only if it can be rendered in the local time zone

### PR DESCRIPTION
**Pull request by itisAliRH**
Fixes #15301
image

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/UtcDate.vue [hunk 1]
```diff
@@ -12,13 +11,12 @@ const props = withDefaults(defineProps<UtcDateProps>(), {
     mode: "date",
 });
 
-// Component assumes ISO format date, but note that in Galaxy this won't have
-// TZinfo -- it will always be Zulu
 const parsedDate = computed(() => parseISO(`${props.date}Z`));
 const elapsedTime = computed(() => formatDistanceToNow(parsedDate.value, { addSuffix: true }));
 const fullISO = computed(() => parsedDate.value.toISOString());
-const pretty = computed(() => `${formatInTimeZone(parsedDate.value, "Etc/Zulu", "eeee MMM do H:mm:ss yyyy")} UTC`);
+const pretty = computed(() => `${format(parsedDate.value, "eeee MMM do H:mm:ss yyyy zz")}`);
```
Comment (nsoranzo) [inline client/src/components/UtcDate.vue]: What about using the combination of long localized date and time?

```suggestion
const pretty = computed(() => `${format(parsedDate.value, "PPPPpppp")}`);
```

File: client/src/components/DatasetInformation/DatasetInformation.test.js [hunk 2]
```diff
@@ -67,7 +66,7 @@ describe("DatasetInformation/DatasetInformation", () => {
     it("Date should be formatted", async () => {
         const date = datasetInfoTable.find(".utc-time").text();
         const parsedDate = parseISO(`${datasetResponse.create_time}Z`);
-        const formattedDate = `${formatInTimeZone(parsedDate, "Etc/Zulu", "eeee MMM do H:mm:ss yyyy")} UTC`;
+        const formattedDate = `${format(parsedDate, "eeee MMM do H:mm:ss yyyy zz")}`;
```
Comment (ElectronicBlueberry) [inline client/src/components/DatasetInformation/DatasetInformation.test.js]:
```suggestion
        const formattedDate = format(parsedDate, "eeee MMM do H:mm:ss yyyy zz");
```

**Comment by martenson** [comment]
this seems worth fixing, could you please react to the comments and push this forward @itisAliRH ?

File: client/src/components/UtcDate.vue (hunk 1 above)
Comment (itisAliRH) [reply client/src/components/UtcDate.vue]: Both options yield the same outcome, but I prefer the current one because it is easier to read.

**Comment by itisAliRH** [comment]
> this seems worth fixing, could you please react to the comments and push this forward @itisAliRH ?

Thanks for pointing out the issues @martenson . I've addressed the comments and pushed the updated changes forward.

File: client/src/components/UtcDate.vue (hunk 1 above)
Comment (nsoranzo) [reply client/src/components/UtcDate.vue]: @itisAliRH Sorry I missed your reply since I wasn't tagged and didn't notice you were replying to my old comment.

The two patterns don't yield the same outcome, see the following examples:

```js
import { format } from "date-fns";
import { it } from "date-fns/locale";

format(new Date(2014, 0, 11), 'eeee MMM do H:mm:ss yyyy zz')  // Saturday Jan 11th 0:00:00 2014 GMT+0
format(new Date(2014, 0, 11), 'PPPPpppp')  // Saturday, January 11th, 2014 at 12:00:00 AM GMT+00:00
format(new Date(2014, 0, 11), 'eeee MMM do H:mm:ss yyyy zz', { locale: it })  // sabato gen 11 0:00:00 2014 GMT+0
format(new Date(2014, 0, 11), 'PPPPpppp', { locale: it })  // sabato 11 gennaio 2014 00:00:00 GMT+00:00
```

from which we can see that 'PPPPpppp' has the following advantages:
- The year is kept part of the date and not put between the time and timezone
- The time is localised too.
- The order of day of the month and month is localised (in Europe we write the day before the month)

Comment (dannon) [reply client/src/components/UtcDate.vue]: @nsoranzo: Sorry I missed this conversation hadn't resolved.  What about `PPPppp`?

This seems even better to me as a natural yet more concise display of a timestamp I'd expect it an application.

```
Sunday, July 2nd, 2023 at 2:44:16 PM GMT-04:00 
vs 
July 2nd, 2023 at 2:44:16 PM GMT-4
```

Comment (nsoranzo) [reply client/src/components/UtcDate.vue]: Not a strong opinion, but sometimes it's convenient to know straightaway the day of the week (e.g. of when you started a job) without having to look at the calendar.
On the other hand screen space is precious, so...

Comment (dannon) [reply client/src/components/UtcDate.vue]: @nsoranzo Yeah, I thought about that a bit and to me it seems like day of the week is relevant for only a brief period of time (<1w).  I guess we could display day if recent, otherwise not, but I think I lean towards consistent brevity?  Only a slight preference, though, if anyone feels strongly I'm fine with whatever :)
