### PR TITLE
[24.0] Fix rules runtime editable

### LINKED ISSUE #18719: Collection builder rules should  not be editable at runtime
You can currently do this in the UI, ending up with

Sentry Issue: [GALAXY-MAIN-ZR3](https://sentry.galaxyproject.org/organizations/galaxy/issues/159837/?referrer=github_integration)

```
TypeError: 'RuntimeValue' object is not subscriptable
  File "galaxy/web/framework/decorators.py", line 346, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "galaxy/webapps/galaxy/api/workflows.py", line 549, in build_module
    "outputs": module.get_all_outputs(),
  File "galaxy/workflow/modules.py", line 1950, in get_all_outputs
    rule_set = RuleSet(rules)
  File "galaxy/util/rules_dsl.py", line 528, in __init__
    self.raw_rules = rule_set_as_dict["rules"]

Uncaught exception in exposed API method:
```

### PR DESCRIPTION
**Pull request by ElectronicBlueberry**
Fixes #18719

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/Workflow/Editor/Forms/FormTool.vue [hunk 1]
```diff
@@ -128,6 +128,9 @@ export default {
             return !!this.configForm?.id;
         },
         inputs() {
+            // TODO: Refactor
+            // This code contains a computed side-effect and prop mutation.
+            // Both should be refactored
```
Comment (mvdbeek) [inline client/src/components/Workflow/Editor/Forms/FormTool.vue:133]: 👍

**Comment by mvdbeek** [comment]
Thanks a lot!
