### PR TITLE
[22.05] History animation method change, constrained info box

### LINKED ISSUE #14098: [release-testing] New history hides peek when stdout too large
**Describe the bug**
Similar to #14014. The size of the expansion is limited but does not account for large stdouts. As a consequence the expanded history item is cut off and this can lead to glitches with the virtual scroller.

**Expected behavior**
The stdout should be limited to only a few lines.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by dannon**
Instead of custom animations this swaps to the bootstrap collapse directive.  We have (slightly) less control over this, but it animation speed is now consistent across the application for all things using the directive.  Additionally, we don't have to fiddle with element height directly, which avoids issues with having giant dataset info blocks that push details past max-height. (fixes https://github.com/galaxyproject/galaxy/issues/14098 and https://github.com/galaxyproject/galaxy/issues/14014)

Also constrains the info box to a max height of 4 lines, scrolling past that.

## How to test the changes?
- [x] Instructions for manual testing are as follows:
  1. Toggle history items open/closed; try one with a gigantic 'info' field and note it opens all the way.

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

File: client/src/components/History/Content/Dataset/DatasetDetails.vue [hunk 1]
```diff
@@ -22,21 +22,52 @@
...
         </div>
+        <div v-else class="dataset">
+            <!--
+                placeholder skeleton for loading smoothly without a spinner
+                (which you don't even see since this happens pretty fast)
+            -->
+            <div class="p-2 details">
+                <div class="summary">
+                    <div class="mb-1">
+                        <b-skeleton width="85%"></b-skeleton>
```
Comment (guerler) [inline client/src/components/History/Content/Dataset/DatasetDetails.vue]: This is neat but in this case it leads to flickering for me because its too fast.

Comment (dannon) [reply client/src/components/History/Content/Dataset/DatasetDetails.vue]: The placeholder goes away too fast, or the animation moves too fast?

The problem I'm trying to work around here is that we want the animation to start as soon as the click happens for a satisfying interaction there.  We fire the details request and need a placeholder of some sort approximating the space that will be used by the resultant details to animate against, but we can't know that perfectly.

**Comment by nsoranzo** [comment]
@dannon I see you added this to the 22.05 milestone, do you want to target the release_22.05 branch?

**Comment by mvdbeek** [comment]
Thank you, that should also fix the issue @jennaj reported that came in via the bugs mailing list.
