### PR TITLE
Fix handling of collection element identifiers in history panel

### LINKED ISSUE #10311: scratchbook with dataset collection oddity
Sorry for not knowing a better title for this, but what I found is this:
When you have a collection and you're trying to view one of the datasets contained within it with the scratchbook enabled, then what's getting displayed are the contents of what seems to be a random other dataset (maybe even from other users?).
When you view the same dataset without the scratchbook, or with the scratchbook but the dataset expanded first, then things work as they should.

### PR DESCRIPTION
**Pull request by guerler**
Fixes #10311 and #10328.

### CODE REVIEW

File: client/src/mvc/dataset/dataset-li-edit.js [hunk 1]
```diff
@@ -66,8 +66,9 @@ var DatasetListItemEdit = _super.extend(
                     const Galaxy = getGalaxyInstance();
                     if (Galaxy.router) {
                         ev.preventDefault();
+                        const identifier = self.model.get("element_id") || self.model.get("id");
                         Galaxy.router.push("datasets/edit", {
-                            dataset_id: self.model.attributes.id,
+                            dataset_id: identifier,
```
Comment (mvdbeek) [inline client/src/mvc/dataset/dataset-li-edit.js:71]: `element_id` refers to `DatasetCollectionElement` instances, which you can't mix with HDA ids (`self.model.get("id")`). Unless the model change is taken into account elsewhere you're just going to display a random dataset (if it is not private).

Comment (guerler) [reply client/src/mvc/dataset/dataset-li-edit.js:71]: Interesting. Thank you for looking into this. I assumed that all model attributes starting with `element_` are specific to that element e.g. `element_type` is `hda`. `element_name` also seems to be correct. Would that not mean that the `element_id` is inconsistent? How else can we retrieve the actual hda identifier?

Comment (mvdbeek) [reply client/src/mvc/dataset/dataset-li-edit.js:71]: Let me look into this to verify I'm not making this more complicated than necessary. In general `DatasetCollectionElement`  instances can be `hda` or `hdca`, and element id should refer to the id of a `DatasetCollectionElement`. From the dataset collection element you can get the dataset, so I would change https://github.com/guerler/galaxy/blob/4db6cc3c31c52a5ff5f3af43700a4e1fdda269b3/lib/galaxy/webapps/galaxy/controllers/dataset.py#L190 to accept element_id. But let me see if we don't already have access to the hda id at this point.

Comment (mvdbeek) [reply client/src/mvc/dataset/dataset-li-edit.js:71]: OK, this is correct because of https://github.com/guerler/galaxy/blob/4db6cc3c31c52a5ff5f3af43700a4e1fdda269b3/client/src/mvc/collection/collection-model.js#L69 ... which is maybe not a good idea because we actually have something that is the element_id, while in this piece of code element_id is either a HDA id or HDCA id. Pretty confusing and that tripped me up. Still, as a bugfix this is fine.

**Review by mvdbeek — APPROVED** [review]
If you pull it out of draft I'm happy to merge!

File: client/src/mvc/dataset/dataset-li-edit.js (hunk 1 above)
Comment (guerler) [reply client/src/mvc/dataset/dataset-li-edit.js:71]: Cool, thanks for double checking it.

**Comment by mvdbeek** [comment]
We should probably Backport this until 20.01
