### PR TITLE
[24.2] Do not reorder options in FormSelect component when multiselect disabled

### LINKED ISSUE #19804: Selects: currently selected option is shown last
**Describe the bug**

Somehow select options confused me since the re-layout and I was wondering for a long time why. In the following select the `Protist...` db is chosen (importantly its the first of the options in the select)

Image

if the user clicks the select the current choice is not visible because it is shown last .. but there is a highlight on hover. 

Image

this is because the selected option is always moved to the end. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.2

**To Reproduce**

The above example is for dada2 assignTaxonomy on eu.

**Expected behavior**

I would suggest to either

- do not change the order of the options 
- show the current selection on top

### PR DESCRIPTION
**Pull request by jdavcs**
Fix #19804

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by ahmedhamidawan** [comment]
Is it just me or the currently selected value is not even being highlighted?:

firefox_zzSSC1YsGV

**Comment by jdavcs** [comment]
> Is it just me or is the currently selected value not even being highlighted?:

You're right! 24.2, on main. It's a different issue though, I think.

**Comment by ahmedhamidawan** [comment]
There is a problem with the multiselect itself as well as `FormSelect` being unable to recognize if something is selected if the select values are objects as opposed to strings/numbers etc.

**Comment by ahmedhamidawan** [comment]
Note that this commit https://github.com/galaxyproject/galaxy/pull/19837/commits/165cff939ffed0061d067923154b8e35efe18962 not fix the fact that `Multiselect` is still unable to track which values are current because it has the prop `track-by="value"` and value in this case can be an object.

**Comment by ahmedhamidawan** [comment]
Now, explicitly check if the form select values need to be tracked by ids and it now works as expected; the current value(s) are highlighted and ordered accordingly:

firefox_IRZfj1MHhL

**Comment by bernt-matthias** [comment]
Results look great, but I wont be able to review this .. I have no clue about the client stuff :(

**Comment by ahmedhamidawan** [comment]
Also changed the hover highlight for the current option to `brand-sucess` from `brand-danger` which I think makes more sense? Can drop this commit if people are against this.

firefox_8LGhaPTat6

**Comment by jdavcs** [comment]
@ahmedhamidawan I really dislike the red as the "this option is selected" indicator. Do we have an option besides green? (maybe a darker shade of gray, so as to highlight the selected item as "different" from unselected items; red/green, to me, is action or event-related as opposed to indicating a difference) If not, green is still  better than red, in my opinion.

**Comment by jdavcs** [comment]
> Maybe this? @jdavcs

Yep, I think that makes it much better!

File: client/src/components/Form/Elements/FormSelect.vue [hunk 1]
```diff
@@ -114,11 +122,25 @@ const selectedLabel: ComputedRef<string> = computed(() => {
  */
 const selectedValues = computed(() => (Array.isArray(props.value) ? props.value : [props.value]));
 
+/**
+ * Tracks selected ids in case of objects with string ids
+ */
+const selectedIds = computed(() => {
+    return selectedValues.value.map((v) => (isValueWithId(v) ? v.id : undefined)).filter((v) => v !== undefined);
```
Comment (mvdbeek) [inline client/src/components/Form/Elements/FormSelect.vue]: What are those ids ? dataset ids ? Those are not unique, you'd typically have to combine this with `src` or `history_content_type`

Comment (ahmedhamidawan) [reply client/src/components/Form/Elements/FormSelect.vue]: Good point, we can use `itemUniqueKey` here then
