### PR TITLE
Fix tool help headings and sizes

### LINKED ISSUE #14799: Font sizes off?
**Describe the bug**

image

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by ElectronicBlueberry**
Followup for #14549
Fixes #14799

image

ToolHelp now adjusts the heading levels of tool descriptions, and adds heading styles more in-line with the rest of the tool form.
This PR also refactors the ToolHelp component removing jquery, and adds an unit test for the component.

Also relevant for #14622

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/Tool/ToolHelp.vue [hunk 1]
```diff
@@ -1,30 +1,93 @@
...
+
+    const images = node.getElementsByTagName("img");
+    Array.from(images).forEach((image) => {
+        if (image.src.includes("admin_toolshed")) {
+            image.src = getAppRoot() + image.src;
+        }
+    });
+
+    // loop these levels backwards to avoid increasing heading twice
+    [5, 4, 3, 2, 1].forEach((level) => {
```
Comment (guerler) [inline client/src/components/Tool/ToolHelp.vue:29]: Would it not be enough to set the css styles for the `.form-help` section and redefine `h1`, `h2` etc locally?

Comment (ElectronicBlueberry) [reply client/src/components/Tool/ToolHelp.vue:29]: No. Simply restyling the headings would hide the issue without solving it. The heading elements in the help texts are breaking the heading level structure and introducing multiple top-level headings to a page. Pushing them down by two levels should fix the structure for most cases and ensures there cannot be multiple h1 elements on the page.

Comment (bgruening) [reply client/src/components/Tool/ToolHelp.vue:29]: @ElectronicBlueberry what is your recommendation for the tool help for tool authors? We should document this and fix our tools if possible. But some recommendations would be nice. Thanks a bunch.

Comment (ElectronicBlueberry) [reply client/src/components/Tool/ToolHelp.vue:29]: @bgruening  My recommendation is that when using headings, to use h1, h2... headings, without skipping any levels for sub headings. So always start at h1, next sub heading h2, etc.
Essentially treating the headings as if they were in a stand-alone document. (with the exception that multiple h1 tags are fine, because the top-level heading for the help section is provided by the tool from)

I think the best way to document this in a clear manner would be by example "Dos and Don'ts"

Comment (dannon) [reply client/src/components/Tool/ToolHelp.vue:29]: This is how we handled it in the old hub, too actually -- write each doc to stand alone, and the parent context can shift headings to make it correct when embedded.

Markdown linters (since we're moving away from RST?) can tell you "Hey, looks like your headings are not coherent", if we want more firm guidelines I guess?

Comment (bgruening) [reply client/src/components/Tool/ToolHelp.vue:29]: The tool help is currently in RST ... so I guess we need to adopt the recommendations for RST.
Changing tool help to (optionally) markdown was discussed but never implemented I think, or was it?

Comment (dannon) [reply client/src/components/Tool/ToolHelp.vue:29]: @bgruening Yeah, my understanding was that we're going to try to move away from RST to MD but I don't know the timeline or even who wants to drive it.
