### PR TITLE
Limit tool parameter value to show only 20 lines with overflow scrolling

### LINKED ISSUE #13452: Limit size of displayed tool parameter values in datasets details view
When clicking on the `info` icon for an expanded dataset in the history, the dataset details view is displayed. This works well unless one of the tool parameters is a json blob. This json blob can be very large, making scrolling to the bottom difficult and also leading to a lagging user interface. It would be nice if we can also fix the flickering of this view in this context by use of the `LoadingSpan` component.

**Galaxy Version and/or server at which you observed the bug**
In dev and on main.

**To Reproduce**
1. Upload a significant number of datasets using the FTP uploader e.g. 100
2. Select a dataset from the history and click on its title
3. Click on 'info'
4. Notice that the response json parameter contains a large blob

This can also happen in other cases.

**Expected behavior**
The displayed content for tool parameter values should be limited. Maybe using `...` and allowing users to expand the content if needed by clicking.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by itisAliRH**
Fixes #13452
Display content for tool parameter values limited to 20 lines and with overflow scrolling (I think this is a better option than using expand button)

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:
  1. Use the issue `To Reproduce` steps

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

File: client/src/components/JobParameters/JobParameters.vue [hunk 1]
```diff
@@ -138,3 +138,13 @@ export default {
     },
 };
 </script>
+
+<style scoped>
+.tool-parameter-value {
+    overflow: auto;
+    text-overflow: ellipsis;
+    display: -webkit-box;
```
Comment (dannon) [inline client/src/components/JobParameters/JobParameters.vue:146]: I believe postcss should rectify this but it's worth checking to make sure this sets -moz-box or whatever is appropriate there, too.

**Review by dannon — APPROVED** [review]
