### PR TITLE
Beta History: fix history query counts synchronization

### LINKED ISSUE #13749: Total count in bulk operations list incorrect
Might not be reactive?  In new history I've uploaded random text and ran a few jobs.  Then tried to select a few datasets and noticed the following:

image

### PR DESCRIPTION
**Pull request by davelopez**
Fixes #13749

I went overboard trying to fix too many issues in this PR :sweat_smile:
I've simplified this one to the minimum and will create other PRs to address the other issues.

## How to test the changes?
- [x] Instructions for manual testing are as follows:
  - Follow instructions on #13749

  fix

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

File: client/src/store/historyStore/model/watchHistory.js [hunk 1]
```diff
@@ -19,46 +20,134 @@ let lastUpdateTime = null;
...
+ */
+async function requestHistoryChanges(history) {
+    const historyId = history.id;
+    const since = lastRequestDate.toISOString();
+    lastRequestDate = new Date();
+    // First round: request changes affecting currently filtered items and update query stats
+    const data = await requestHistoryChangesWithStatsSince(historyId, since);
+    handleHistoryChanges(history, data);
+    // Second round: request possible additional changes in background
+    requestAllHistoryChangesSince(historyId, since).then((changes) => {
```
Comment (guerler) [inline client/src/store/historyStore/model/watchHistory.js]: Wondering if there are alternatives to this second request here.

File: client/src/components/History/CurrentHistory/HistoryOperations/SelectionStatus.vue [hunk 2]
```diff
@@ -1,10 +1,20 @@
...
     <b-button-group size="sm">
-        <b-button v-if="hasSelection" variant="link" data-test-id="clear-btn" @click="resetSelection">
-            <span class="fa fa-fw fa-times" title="Clear selection" />
+        <b-button
+            v-if="!allSelected"
+            variant="link"
+            data-test-id="select-all-btn"
+            title="Select all"
+            @click="selectAll">
+            <span v-if="!hasSelection">Select </span>All
```
Comment (guerler) [inline client/src/components/History/CurrentHistory/HistoryOperations/SelectionStatus.vue]: Thank you for working on this. Here I noticed that this shifts the selection dropdown to the left and back to the right depending on the selection. This is a lot of motion and I am not sure if its necessary. Previously it was steady.

**Comment by guerler** [comment]
To resolve `may take a second for the history to refresh its contents` we can add the ids to the `invisible` map in the HistoryPanel component. This list will avoid displaying that item until the query `filter` changes. This is already used for deleted/hidden item operations.

File: client/src/store/historyStore/model/watchHistory.js (hunk 1 above)
Comment (davelopez) [reply client/src/store/historyStore/model/watchHistory.js]: The only alternative I can think of right now is to merge both queries in the same request.

Maybe move this kind of response to a new API route like:

```
GET api/histories/{history_id}/changes?since={date}&{filtering_params}
```
This new route can just call the same service method as the index with the right parameters and possibly make the `since` parameter required, probably making more clear the intent.

And modifying the response to something like this:

```jsonc
{
  "since": {date}, // The same date used in the request
  "stats": {
    total_matches: X, // The number of items matching the {filtering_params}
    total_changes: Y, // The number of items updated since {date} ignoring the {filtering_params}
  },
  "history": {
    // The history with updated item counts, etc
  },
  "changes": [
    // contains all changed items since {date}, ignoring the {filtering_params}
  ]
}
```

We can then paginate the changes if necessary using the `since` and the `total_changes` as of right now the number of changes after a bulk operation can be huge and we don't paginate them.

File: client/src/components/History/CurrentHistory/HistoryOperations/SelectionStatus.vue (hunk 2 above)
Comment (davelopez) [reply client/src/components/History/CurrentHistory/HistoryOperations/SelectionStatus.vue]: You are right, I don't like the shifting either, but I think it's important to be able to select all items again in case you change your mind, without having to cancel the selection completely and then start over.
I'll try moving the `Select all` and `Clear` to the left of the selection dropdown to see if it gets 'better' or we can think of another solution :+1:

**Comment by davelopez** [comment]
> To resolve may take a second for the history to refresh its contents we can add the ids to the invisible map in the HistoryPanel component. This list will avoid displaying that item until the query filter changes. This is already used for deleted/hidden item operations.

I tried adding the items to the invisible map but unfortunately, it creates other side effects:
issue-fix3

During that 'second' the scroller is empty (there are no other items in the store, that's why it cannot show them), and also if we restore the hidden items right after, they're still in the `invisible` map. I tried to clear the invisible map after the operation finished, but then we are at square 1 again :disappointed:

File: client/src/store/historyStore/model/watchHistory.js (hunk 1 above)
Comment (davelopez) [reply client/src/store/historyStore/model/watchHistory.js]: These changes are no longer part of this PR, we can follow up with the watch enhancements in a different PR.

File: client/src/components/History/CurrentHistory/HistoryOperations/SelectionStatus.vue (hunk 2 above)
Comment (davelopez) [reply client/src/components/History/CurrentHistory/HistoryOperations/SelectionStatus.vue]: These changes are no longer part of this PR, we can follow up with the watch enhancements in a different PR.

**Comment by davelopez** [comment]
Ok, I dropped most of the other changes and focused only on the total counts' synchronization. It should be easier to review now. Sorry for all the noise :sweat_smile:
