### PR TITLE
[21.09] Add property to disable tool form

### LINKED ISSUE #12576: Dataset collections mixed up internally after applying rules to existing collection
**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09

**To Reproduce**
Follow https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/upload-rules-advanced/tutorial.html#apply-rules-to-existing-collections

At the last step (i.e. after you created the original collection and used Apply Rules twice to build reorganized collections),
try to run Apply Rules again on the original, flat collection.

The rule builder will extract column information from one of the reorganized collections instead of the original, selected one.
Same if you select one of the reorganized ones -> will use identifiers from original collection

**Shared history with the problem**
https://usegalaxy.org/u/wolma/h/test-rule-based

**Screenshots**

**Additional context**
Discovered during 21.09 release testing

### PR DESCRIPTION
**Pull request by guerler**
This resolves #12576. The reason for this issue is that the tool form is waiting for the completion of a server response. The server response contains the new values. If the input element is selected before the server has responded the old value is still displayed in the parameter field.

image

## How to test the changes?
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

File: client/src/components/Tool/ToolForm.vue [hunk 1]
```diff
@@ -226,9 +228,14 @@ export default {
...
-            updateToolFormData(this.formConfig.id, this.currentVersion, this.history_id, this.formData).then((data) => {
-                this.formConfig = data;
-            });
+            this.disabled = true;
+            updateToolFormData(this.formConfig.id, this.currentVersion, this.history_id, this.formData)
+                .then((data) => {
+                    this.formConfig = data;
+                })
+                .finally(() => {
+                    this.disabled = false;
```
Comment (mvdbeek) [inline client/src/components/Tool/ToolForm.vue:237]: Minor point here: should we restore the old formConfig if the request fails ? Otherwise we're still operating on the old input, which might be confusing ?
