### PR TITLE
[22.05] Citation link decoding fix

### LINKED ISSUE #14225: Citation component: decoded URL issue with doi.org
**Describe the bug**
Although the citation component is able to fetch the citation data from the DOI id, I noticed that `doi.org` is not handling decoded URLs (`%252F` instead of `/` symbol) properly resulting in 404 not found HTTP errors when it comes from a link, at least in Google Chrome.

Each citation link is generated by:

https://github.com/galaxyproject/galaxy/blob/1b680cbd05d6257118a333b72b3069bea271aad9/client/src/components/Citation/Citation.vue#L5-L7

Where the link content is the result of:

https://github.com/galaxyproject/galaxy/blob/1b680cbd05d6257118a333b72b3069bea271aad9/client/src/components/Citation/Citation.vue#L34-L37

In my example, this citation was declared inside the tool XML as:

```xml
<citations>
        <citation type="doi">10.1093/bioinformatics/btz912</citation>
```

I managed to "reverse" the encoded URL by doing:

```javascript
        link() {
            const cite = this.citation.cite;
            const encodedUrl = cite.data && cite.data[0] && cite.data[0].URL;
            const reverseEncodingUrl = encodedUrl.replaceAll("%252F", "/");
            return reverseEncodingUrl;
        },
``` 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: `{"version_major":"22.05","version_minor":"dev0"}`
Commit: `fd8826904be3f3201f7e7a3b6ffbadd27f268896`

**To Reproduce**
1. Go to Workflow
2. Click on 'Create' and fill out the basic information about this new WF (name: 'test issue citations', annotation: empty)
3. Click on 'Create' again
4. Add a tool with the citations block included
5. Click on the tool and scroll down until "Citations"
6. Click the link icon to open the citation using the DOI URL

**Expected behavior**
I expect to click on the "View citation" link of a tool and open the citation through the DOI id without receiving 404 HTTP errors. 

**Screenshots**
The citation content was loaded with no issues:
image

However, the URL links to doi.org do not work properly. 

For instance, in the next example, the `href` content is decoded: 

Screenshot 2022-06-29 172646

Link: `https://doi.org/10.1093%252Fbioinformatics%252Fbtz912`
image

After the proposed changes:

image

Link: `https://doi.org/10.1093/bioinformatics/btz912` redirects to `https://academic.oup.com/bioinformatics/article/36/7/2076/5670527`:

image

**Additional context**

### PR DESCRIPTION
**Pull request by dannon**
Fixes #14225

Thanks to @agdiaz for the excellent bug report and debugging!

## How to test the changes?
(Select all options that apply)
- [ ] Instructions for manual testing are as follows:
  1. See linked issue.

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

**Review by davelopez — APPROVED** [review]

**Comment by agdiaz** [comment]
@dannon and @davelopez thank you very much for your time and effort invested in fixing #14225!!! Let's go GalaxyProject 🚀

File: client/src/components/Citation/Citation.vue [hunk 1]
```diff
@@ -22,18 +22,25 @@ export default {
...
         prefix: {
             type: String,
+            default: "",
         },
     },
     computed: {
         link() {
             const cite = this.citation.cite;
-            return cite.data && cite.data[0] && cite.data[0].URL;
+            if (cite.data && cite.data[0] && cite.data[0].URL) {
```
Comment (agdiaz) [inline client/src/components/Citation/Citation.vue]: [Just an anecdotic comment about how JS is evolving]: 

I've discovered some time ago that JS has added in its version `ES2020` a new operator called "Optional chaining" (`?.`) which simplifies the accessing chained properties in a safe way: [mdn web docs entry](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

In this case, it may be applied:

```javascript
link() {
  const cite = this.citation.cite;
  // Simplification of `cite.data && cite.data[0] && cite.data[0].URL`
  const citeUrl = cite?.data?.[0]?.URL;

  return citeUrl ? decodeURIComponent(citeUrl) : null;
}
```

Thank you again for the fix @dannon

Comment (dannon) [reply client/src/components/Citation/Citation.vue]: @agdiaz Thanks!  Yeah, we've used optional chaining in Galaxy before, and it's definitely a clean improvement here; I was just in bugfix and not refactor mode and didn't think about it -- will get that change in now :)
