### PR TITLE
Prepend Galaxy root to dataset download URLs in visualization plugins

### LINKED ISSUE #15047: Galaxy ignores `prefix` for Openlayers visualization plugin
**Describe the bug**
We are using Openlayers visualization tool on a Galaxy instance served at a prefix `/cos`. It seems that the prefix of the Galaxy is being ignored with making an API request to `histories` endpoint. Here is a screenshot of console log of browser

Screenshot_20221122_122834_masked

The failed API request is supposed to be `https://galaxyhost/cos/api/histories/<snippet>`

There was a very similar issue in the past https://github.com/galaxyproject/galaxy/issues/9970

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version:  `22.09-dev0`
Commit: a7d35017d42f78d3f8d46b592402d08be7bb5b56

**To Reproduce**
1. Upload a shape file into Galaxy
2. Click on visualize shape file
3. Click on OpenLayers map
4. Check browser console

**Expected behavior**
Able to visualize the map and plugin making API requests to correct path

### PR DESCRIPTION
**Pull request by mahendrapaipuri**
Most of the visualization plugins use `dataset.download_url` to get datasets for visualizing. This will work only when Galaxy is served without any prefix. This PR prepend Galaxy root to `dataset.download_url` for concerned plugins.

Fixes #15047

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: config/plugins/visualizations/annotate_image/src/script.js [hunk 1]
```diff
@@ -437,11 +437,13 @@ window.bundleEntries.load = function (opt) {
         });
     };
 
+    const slash_cleanup = /(\/)+/g;
+    const safe_download_url = `${options.root}/${dataset.download_url}`.replace(slash_cleanup, "/");
     $.ajax({
-        url: dataset.download_url,
+        url: safe_download_url,
```
Comment (guerler) [inline config/plugins/visualizations/annotate_image/src/script.js:442]: This should probably be fixed in the backend, such that the correct url is provided through the api. It seems to be serialized here: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/managers/hdas.py#L450.

Comment (mahendrapaipuri) [reply config/plugins/visualizations/annotate_image/src/script.js:442]: I thought about it. But when I looked into code base and previous PRs, I have noticed that the Galaxy prefix is added on the client side mostly. I am quite new to Galaxy project so I do not know all the architectural decisions regarding API interfaces. Moreover `url_for` will build the URL based on route and I am not quite sure where the prefix is exposed to prepend the URL returned by `url_for`.

Comment (mvdbeek) [reply config/plugins/visualizations/annotate_image/src/script.js:442]: `download_url` is relative, so if you don't globally set the base url for axios on app load (we should 100% do that) you'll have to add the app prefix in the client

Comment (guerler) [reply config/plugins/visualizations/annotate_image/src/script.js:442]: Ok, yes, this is how it is being handled right now. Thank you for fixing this bug!

**Comment by yvanlebras** [comment]
Youhou !

**Comment by mahendrapaipuri** [comment]
@guerler Is there anything to be done with this PR before merging?

File: config/plugins/visualizations/annotate_image/src/script.js [hunk 2]
```diff
@@ -437,11 +437,13 @@ window.bundleEntries.load = function (opt) {
         });
     };
 
+    const slash_cleanup = /(\/)+/g;
+    const safe_download_url = `${options.root}/${dataset.download_url}`.replace(slash_cleanup, "/");
```
Comment (mvdbeek) [inline config/plugins/visualizations/annotate_image/src/script.js]:
```suggestion
    const safe_download_url = `${options.root}${dataset.download_url}`;
```
or `${getAppRoot()}/${dataset.download_url}`, which we use throughout the app

**Review by dannon — APPROVED** [review]
