### PR TITLE
Use timeout instead of interval when polling, optionally terminate polling

### LINKED ISSUE #13415: View details page does not update when job completes
**Describe the bug**
If you start a job and click the info icon to View details before the job completes, then click it again after the job completes, you see the same information. If you only click the View details icon after the job completes, different information is shown. So the view details page is not updating the new information after the job completes if it's clicked it before the job completes.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.01
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Start a job (could even be to upload a dataset)
2. Before the job completes, click on the View details (info) icon 
3. Start the same job
4. After the job completes, click on the View details (info) icon
5. Compare results from View details from step (4) to step (2), notice the differences.

**Expected behavior**
Expect View details information to be the same after the job completes, even when clicked again on the same history item if it was clicked before the job started.

**Screenshots**

Dataset 19 - clicked on icon before job completed, screenshot when opened again after job completed.
Screen Shot 2022-02-18 at 5 09 23 PM

Dataset 20 - same upload job as 19, clicked on View details icon only after job completed
Screen Shot 2022-02-18 at 5 09 15 PM

**Additional context**
Also happens in AnVIL. Refreshing history doesn't fix it.

### PR DESCRIPTION
**Pull request by mvdbeek**
Depending on the response time using setInterval can lead to a pileup of
requests, see
https://developer.mozilla.org/en-US/docs/Web/API/setInterval#ensure_that_execution_duration_is_shorter_than_interval_frequency.
We've already had issues with this before.

Fixes https://github.com/galaxyproject/galaxy/issues/13415

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

### CODE REVIEW

File: client/src/components/providers/DatasetProvider.js [hunk 1]
```diff
@@ -24,4 +25,4 @@ async function getDatasetAttributes({ id }) {
 }
 
 export const DatasetAttributesProvider = SingleQueryProvider(getDatasetAttributes);
-export default SingleQueryProvider(getDataset);
+export default SingleQueryProvider(getDataset, stateIsTerminal);
```
Comment (guerler) [inline client/src/components/providers/DatasetProvider.js:28]: This means that a dataset is not updated if e.g. the dataset attributes such as build or datatype change but I still think that this approach is better for now since it helps resolving the current problem of piling requests. Edit: Also we could probably force a refresh by changing the `key` property to trigger a new polling session on metadata change.

**Review by guerler — APPROVED** [review]

File: client/src/components/providers/DatasetProvider.js (hunk 1 above)
Comment (mvdbeek) [reply client/src/components/providers/DatasetProvider.js:28]: Piling up requests is because `setInterval` just fires off in a given interval, that is not why I changed this. We can't poll forever for dataset changes, that is too heavy on the server.

Comment (mvdbeek) [reply client/src/components/providers/DatasetProvider.js:28]: A better solution In a history context is that ideally you'd watch for updates in a central polling scheme. When updates come in you'd update a central store with the datasets that have changed, and the single item providers would then automatically get the update. That is what pouchdb did for us previously.
