### PR TITLE
[23.0] Fix backbone-based data selector to materialize consistent attribute set

### LINKED ISSUE #10402: Display some kind of warning when rerun would change params used
https://github.com/galaxyproject/galaxy/issues/9002 describes a situation where a direct column select is unavailable in a tool interface and the user has to enter an integer instead.
Another aspect of this is that when you try to rerun such a job, that integer is lost from the repopulated tool interface, and if uncorrected the rerun may actually run with *different* settings than the first job.

There should probably be some kind of colorful warning about this going to happen in the tool interface?

### PR DESCRIPTION
**Pull request by guerler**
Fixes #10402. Currently the content selector populates the value with `id`, `src` and `name` and other custom attributes. The backend however only requires `id`, `src` and `map_over_type` as actual input values for job runs, this leads to value changes which trigger build requests and prevent the error highlighting from being displayed properly. This PR fixes this in the backbone-based by ensuring that the input element only materializes the `id`, `src` attributes in the value. This dramatically reduces the number of tool build requests.

However as a consequence, the tool run success message does now only display the output datasets but not the input datasets anymore. This should not be an issue tho, since the inputs are known to the user who has selected them in the tool form and can be displayed again when clicking either on the info icon or the re-run button.

The highlighting here is a first step, moving forward we can consider to relax the condition and re-populate the original dataset with a warning e.g. saying that it is currently deleted or for some other reason unavailable.

This fix is applied to the backbone-based data selector input element which we should replace with a Vue component as soon as possible.

image

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/Tool/ToolSuccess.vue [hunk 1]
```diff
@@ -1,42 +1,45 @@
...
 import { useJobStore } from "@/stores/jobStore";
 import { useRouter } from "vue-router/composables";
-import { getGalaxyInstance } from "@/app";
 import ToolEntryPoints from "@/components/ToolEntryPoints/ToolEntryPoints.vue";
-import ToolSuccessMessage from "./ToolSuccessMessage.vue";
 import ToolRecommendation from "../ToolRecommendation.vue";
+import ToolSuccessMessage from "./ToolSuccessMessage.vue";
 import Webhook from "@/components/Common/Webhook.vue";
 
+const { config } = useConfig();
```
Comment (mvdbeek) [inline client/src/components/Tool/ToolSuccess.vue]:
```suggestion
const { config } = useConfig(true);
```

File: client/src/components/Tool/ToolSuccess.vue [hunk 2]
```diff
@@ -1,42 +1,45 @@
...
             <ToolEntryPoints v-for="job in jobResponse.jobs" :key="job.id" :job-id="job.id" />
         </div>
-        <ToolSuccessMessage :job-def="jobDef" :job-response="jobResponse" :tool-name="toolName" />
+        <ToolSuccessMessage :job-response="jobResponse" :tool-name="toolName" />
         <Webhook type="tool" :tool-id="jobDef.tool_id" />
         <ToolRecommendation v-if="showRecommendation" :tool-id="jobDef.tool_id" />
     </section>
+    <section v-else>
+        <b-alert v-localize show variant="info">
+            The last job details are not available anymore, but you can obtain this information by accessing the
```
Comment (mvdbeek) [inline client/src/components/Tool/ToolSuccess.vue]: I don't think I would understand what that means, and when this would be the case ... is it necessary ?

**Comment by mvdbeek** [comment]
I don't think it fixes https://github.com/galaxyproject/galaxy/issues/10402:

re-run picks different dataset

File: client/src/components/Tool/ToolForm.vue [hunk 3]
```diff
@@ -43,6 +43,7 @@
                                 <FormDisplay
                                     :id="toolId"
                                     :inputs="formConfig.inputs"
+                                    :errors="formConfig.warnings || {}"
```
Comment (mvdbeek) [inline client/src/components/Tool/ToolForm.vue]: I think you need to include errors as well:
Screenshot 2023-05-18 at 16 42 52

that doesn't fix the wrong dataset selection, but this is probably also required. Given the complex interaction between backend and frontend an end-to-end test is probably a good idea here.

Comment (guerler) [reply client/src/components/Tool/ToolForm.vue]: Thanks for looking into this. When I try it this is the result:



https://github.com/galaxyproject/galaxy/assets/2105447/5ae704cc-ff8c-4a5e-a1d1-3966f19ec859


This needs a test case anyway, I'll add that and then we go from there.

Comment (guerler) [reply client/src/components/Tool/ToolForm.vue]: I added a test to verify that this works.

File: client/src/components/Tool/ToolSuccess.vue (hunk 2 above)
Comment (guerler) [reply client/src/components/Tool/ToolSuccess.vue]: I added this as a fallback since the previous statement also specifies an explicit if-condition, but that statement is likely also unnecessary. Removed the alert.

File: client/src/components/Tool/ToolForm.vue (hunk 3 above)
Comment (guerler) [reply client/src/components/Tool/ToolForm.vue]: Also added the initial errors to the form initialization.

File: lib/galaxy_test/selenium/test_tool_form.py [hunk 4]
```diff
@@ -114,6 +114,28 @@ def check_recorded_val():
         self.history_panel_wait_for_hid_ok(2)
         self._check_dataset_details_for_inttest_value(2)
 
+    @selenium_test
+    def test_rerun_deleted_dataset(self):
+        # upload a first dataset that should not become selected on re-run
+        test_path = self.get_filename("1.tabular")
+        self.perform_upload(test_path)
+        self.history_panel_wait_for_hid_ok(1)
+        self.tool_open("column_param")
```
Comment (mvdbeek) [inline lib/galaxy_test/selenium/test_tool_form.py:123]: Select a non-default column here please (and one that isn't available on the input that gets selected in place of the deleted hid 1)

File: lib/galaxy_test/selenium/test_tool_form.py [hunk 5]
```diff
@@ -114,6 +114,28 @@ def check_recorded_val():
...
+        item.delete_button.wait_for_and_click()
+        item = self.history_panel_item_component(hid=2)
+        item.title.wait_for_and_click()
+        item.rerun_button.wait_for_and_click()
+        # validate form error text
+        input_warning = self.components.tool_form.parameter_error(parameter="input1").wait_for_visible()
+        assert (
+            input_warning.text
+            == "parameter 'input1': the previously selected dataset has been deleted. Using default: ''."
+        )
```
Comment (mvdbeek) [inline lib/galaxy_test/selenium/test_tool_form.py:139]: You want to verify that there's an error message on the column parameter as well.

**Review by mvdbeek — APPROVED** [review]
I think this works well ... it feels odd that the warning message doesn't go away, but if you have multiple warnings I guess that's the only way that makes sense ?

**Review by mvdbeek — APPROVED** [review]
I think this works well ... it feels odd that the warning message doesn't go away, but if you have multiple warnings I guess that's the only way that makes sense ?

**Comment by guerler** [comment]
Thanks for your help and review, and yes, I think so too. We could however modify how warnings are shown. Maybe a highlighted exclamation mark with a tooltip is sufficient, and then maybe we can even show it together with actual form errors.

**Comment by mvdbeek** [comment]
I suppose another way is to show a `X` to dismiss the warning, and/or dismiss the warning once a user has clicked a field ... but that seems like a significant change.
