### PR TITLE
[24.1] Add copy link to published workflow in `WorkflowCard`

### LINKED ISSUE #18368: Workflow cards view should provide a way to share links to published WFs
**Describe the bug**
Reported originally by @nomadscientist; currently I cannot find any way to share the link to a published workflow from the workflow cards view.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: any Galaxy version since introduction of WF cards

### PR DESCRIPTION
**Pull request by itisAliRH**
Closes #18368. This PR adds a new action button to the `WorkflowCard` which shows on published workflows for copying the link to the workflow on click and also replaces the imported from URL indicator on `WorkflowIndicators` with `faFileImport` that had conflict with the new button icon.

image
image

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

File: client/src/components/Workflow/WorkflowActionsExtend.vue [hunk 1]
```diff
@@ -72,11 +65,41 @@ async function onRestore() {
         Toast.info("Workflow restored");
     }
 }
+
+const root = computed(() => {
+    const port = window.location.port ? `:${window.location.port}` : "";
```
Comment (mvdbeek) [inline client/src/components/Workflow/WorkflowActionsExtend.vue]: If you search for `window.location.port` you find other instances of this, maybe you could push this to a shared helper function ?

File: client/src/components/Workflow/WorkflowActionsExtend.vue [hunk 2]
```diff
@@ -72,11 +65,41 @@ async function onRestore() {
...
+    copy(fullLink.value);
+    Toast.success("Link to workflow copied");
+}
 </script>
 
 <template>
     <div class="workflow-actions-extend flex-gapx-1">
         <BButtonGroup>
+            <BButton
+                v-if="!isAnonymous && workflow.published && !workflow.deleted"
```
Comment (mvdbeek) [inline client/src/components/Workflow/WorkflowActionsExtend.vue]: Does this mean anonymous users can't copy the link ? Why is that ?

File: client/src/components/Workflow/WorkflowActionsExtend.vue (hunk 1 above)
Comment (itisAliRH) [reply client/src/components/Workflow/WorkflowActionsExtend.vue]: I created a `getFullAppUrl` util function and replaced all instances of `window.location.port` with it where needed.

File: client/src/components/Workflow/WorkflowActionsExtend.vue (hunk 2 above)
Comment (itisAliRH) [reply client/src/components/Workflow/WorkflowActionsExtend.vue]: Good catch! The condition was copied from another button and wasn’t necessary here, so I’ve removed it. Thanks for pointing it out.

**Review by mvdbeek — APPROVED** [review]

**Comment by mvdbeek** [comment]
Awesome, thank you!
