### PR TITLE
Adjust dataset error reporting page, remove email option, remove long info text

### LINKED ISSUE #9296: Bug reporting page asks for email even when logged in
There are two issues here. One is that it doesn't seem necessary to ask for the email since we already know what it is. The second is that the user can enter an arbitrary email, which means you could potentially spam someone with it. The behaviour seems particularly desirable when `require_login=True`, and/or `user_activation_on=True`, since the user email on record is guaranteed to be correct.

### PR DESCRIPTION
**Pull request by guerler**
Fixes #9296. This PR simplifies the error reporting page, the email information is redundant and should be changed in the User Preference view, if necessary. Also this PR removes the statements referring to the "usual" behavior of a Galaxy Administrator. Error reporting can be very helpful and, in my opinion should be made as easy as possible, even if administrators might not be able to respond adequately to all reports in due time. This PR also makes minor title and style adjustments to the error reporting page.

### CODE REVIEW

**Comment by nsoranzo** [comment]
I think this will prevent anonymous users from reporting issues?

File: client/galaxy/scripts/mvc/dataset/dataset-error.js [hunk 1]
```diff
@@ -173,50 +170,26 @@ var View = Backbone.View.extend({
...
-        */
-
-        var form = new Form({
-            title: _l("Error Report"),
-            inputs: inputs,
+        const form = new Form({
+            inputs: [
+                {
+                    type: "text",
+                    hidden: true,
```
Comment (nsoranzo) [inline client/galaxy/scripts/mvc/dataset/dataset-error.js]: Can you make this hidden only if the user is not anonymous? Otherwise they won't be able to insert their email address to receive a reply.

I'd leave it not-hidden for all users, so one could choose a different email address to receive this kind of emails.

Comment (guerler) [reply client/galaxy/scripts/mvc/dataset/dataset-error.js]: I enabled the email for anonymous users although I am not sure how useful dataset error reporting is for an anon user, since the session will be cleared.

**Comment by guerler** [comment]
@nsoranzo thanks for the comments, I have applied the changes.

**Review by nsoranzo — APPROVED** [review]
