### PR TITLE
Warning when importing published history by URL

### LINKED ISSUE #15100: Export history to different instance by URL
**Describe the bug**

When trying to export a history from *eu to *org.au I got this error:

```
Traceback (most recent call last): File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/imp_exp/unpack_tar_gz_archive.py", line 92, in <module> main(options, args) File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/imp_exp/unpack_tar_gz_archive.py", line 73, in main check_archive(archive_file, dest_dir) File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/imp_exp/unpack_tar_gz_archive.py", line 38, in check_archive with tarfile.open(archive_file, mode="r") as archive_fp: File "/usr/lib/python3.8/tarfile.py", line 1608, in open raise ReadError("file could not be opened successfully") tarfile.ReadError: file could not be opened successfully
```

**Galaxy Version and/or server at which you observed the bug**
"version_major":"22.05","version_minor":"1"

**To Reproduce**
1. Copy this URL from a shared and published history: https://usegalaxy.eu/u/gallardoalba/h/srp201920salmon-1
2. Import it in usegalaxy.org.au: Users/Histories/Import history/Export URL from another Galaxy instance

**Expected behavior**
The history should be shared.

**Screenshots**

Screenshot from 2022-12-01 19-42-25

**Additional context**

### PR DESCRIPTION
**Pull request by ElectronicBlueberry**
Closes #15100

Adds a warning when attempting  to import a history which has not been exported to an archive.

image

Warning does not appear for archive links. Only for links following a `/user/ ... /history/ ...` pattern.

## How to test the changes?
(Select all options that apply)
- [x] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

File: client/tests/jest/helpers.js [hunk 1]
```diff
@@ -146,7 +146,13 @@ export const showAll = (vm) => {
 
 // waits n milliseconds and then promise resolves
 // usage: await wait(500);
-export const wait = (n) => timer(n).pipe(take(1)).toPromise();
+export const wait = (n) => {
```
Comment (dannon) [inline client/tests/jest/helpers.js:149]: Thanks for this -- always feel free to cut out any of the rxjs-isms you find; I'd like to get rid of it eventually.

**Review by dannon — APPROVED** [review]

**Comment by martenson** [comment]
but where is Clippy? 👀
